#ifndef DRUMS_KIT1_H
#define DRUMS_KIT1_H

#include "AudioSampleClosedhh.h"
#include "AudioSampleClosedhh40msw.h"
#include "AudioSampleCowbell.h"
#include "AudioSampleCowbell100msw.h"
#include "AudioSampleCowbell40msw.h"
#include "AudioSampleKick.h"
#include "AudioSampleKick40msw.h"
#include "AudioSampleOpenhh.h"
#include "AudioSampleOpenhh100msw.h"
#include "AudioSampleOpenhh40msw.h"
#include "AudioSampleLowcongaw.h"
#include "AudioSampleLowconga100msw.h"
#include "AudioSampleLowconga40msw.h"
#include "AudioSampleRimshot.h"
#include "AudioSampleRimshot40msw.h"
#include "AudioSampleSnare.h"
#include "AudioSampleSnare40msw.h"
#include "AudioSampleTabla1.h"
#include "AudioSampleTabla1100msw.h"
#include "AudioSampleTabla140msw.h"
#include "AudioSampleTabla2.h"
#include "AudioSampleTabla2100msw.h"
#include "AudioSampleTabla240msw.h"
#include "AudioSampleTabla3.h"
#include "AudioSampleTabla3100msw.h"
#include "AudioSampleTabla340msw.h"
#include "AudioSampleTabla4.h"
#include "AudioSampleTabla4100msw.h"
#include "AudioSampleTabla440msw.h"
#include "AudioSampleTabla5.h"
#include "AudioSampleTabla5100msw.h"
#include "AudioSampleTabla540msw.h"

#endif