#ifndef DRUMS_KIT2_H
#define DRUMS_KIT2_H

#include "AudioSampleTuck200ms.h"
#include "AudioSampleTuck140ms.h"
#include "AudioSampleTuck40ms.h"
#include "AudioSampleTonk140ms.h"
#include "AudioSampleTonk40ms.h"
#include "AudioSampleTack100ms.h"
#include "AudioSampleTack40ms.h"
#include "AudioSampleMaracas250ms.h"
#include "AudioSampleMaracas140ms.h"
#include "AudioSampleMaracas40ms.h"
#include "AudioSampleLowperca200ms.h"
#include "AudioSampleLowperca140ms.h"
#include "AudioSampleLowperca40ms.h"
#include "AudioSampleLowperc100ms.h"
#include "AudioSampleLowperc40ms.h"
#include "AudioSampleKick80ms.h"
#include "AudioSampleKick40ms.h"
#include "AudioSampleCrash1000ms.h"
#include "AudioSampleCrash400ms.h"
#include "AudioSampleCrash140ms.h"
#include "AudioSampleCastagnette10ms.h"
#include "AudioSampleCabasa140ms.h"
#include "AudioSampleCabasa100ms.h"
#include "AudioSampleCabasa40ms.h"
#include "AudioSampleBodhran200ms.h"
#include "AudioSampleBodhran140ms.h"
#include "AudioSampleBodhran40ms.h"
#include "AudioSampleBasque250ms.h"
#include "AudioSampleBasque140ms.h"
#include "AudioSampleBasque40ms.h"

#endif