#include "Presets.h"

// ========== PRESETS PRÉDÉFINIS ==========
const Preset DEFAULT_PRESETS[NUM_PRESETS] = {
// Preset saxo
{
    .sound = {
        .type = SYNTH,
        .name = "saxo",
        .synth = {
            .waveformType = 1,
            .amplitude = 0.7,
            .attack = 44,
            .decay = 50,
            .sustain = 0.5,
            .release = 200,
            .freqMod = 0.0,
            .phaseMod = 0.0,
            .ratioFm = 0.0,
            .modAmplitude = 0.0,
            .moogAttack = 10,
            .moogDecay = 50,
            .moogSustain = 0.6,
            .moogRelease = 100.0,
            .lpfResonance = 0.0,
            .octaveShift = 2,
            .lpfCutoff = 5418.24,
            .lpfEnvAmount = 0.5,
            .FMEnvAmount = 0.26,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = -1,
            .wavetable = 0,
        },
    },

    .effects = {
        .reverbRoomSize = 0.5,
        .reverbDamping = 0.54,
        .filterFreq = 2808.53,
        .filterResonance = 0.29,
        .nChorus = 2,
        .tremoloWaveform = 0,
        .tremoloRate = 0.44,
        .tremoloAmplitude = 0.3,
        .moogLfoWaveform = 0,
        .moogLfoRate = 0.5,
        .moogLfoAmplitude = 0.4,
        .noiseAmplitude = 0.46,
        .noiseCutoff = 2794.12,
        .noiseResonance = 0.21,
        .noiseEnvAttack = 279,
        .noiseEnvDecay = 200,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 100,
        .noiseCutoffEnvAmount = 1.1,
        .noiseFilterType = 1,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 2,
        .moogCutoff = 5000.0,
        .moogResonance = 0.18,
    },

    .presetName = "saxo",
    .soundTypeIndex = 0
},
// Preset Deep Bass   
{
    .sound = {
        .type = SYNTH,
        .name = "Deep Bass",
        .synth = {
            .waveformType = 1,
            .amplitude = 0.56,
            .attack = 5,
            .decay = 100,
            .sustain = 0.5,
            .release = 300,
            .freqMod = 0.57,
            .phaseMod = 0.0,
            .ratioFm = 0.5,
            .modAmplitude = 0.4,
            .moogAttack = 5,
            .moogDecay = 80,
            .moogSustain = 0.8,
            .moogRelease = 200.0,
            .lpfResonance = 0.7,
            .octaveShift = 0,
            .lpfCutoff = 1193.53,
            .lpfEnvAmount = 0.93,
            .FMEnvAmount = 0.97,
            .FMWaveform = 1,
            .lpfOctaveControl = 0,
            .FMwavetable = -1,
            .wavetable = 0,
        },
    },

    .effects = {
        .reverbRoomSize = 0.2,
        .reverbDamping = 0.18,
        .filterFreq = 3982.65,
        .filterResonance = 0.59,
        .nChorus = 0,
        .tremoloWaveform = 0,
        .tremoloRate = 1.32,
        .tremoloAmplitude = 0.6,
        .moogLfoWaveform = 0,
        .moogLfoRate = 1.03,
        .moogLfoAmplitude = 0.22,
        .noiseAmplitude = 0.1,
        .noiseCutoff = 200.0,
        .noiseResonance = 0.38,
        .noiseEnvAttack = 20,
        .noiseEnvDecay = 100,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 100,
        .noiseCutoffEnvAmount = 0.79,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 0,
        .moogCutoff = 1617.65,
        .moogResonance = 0.26,
    },

    .presetName = "Deep Bass",
    .soundTypeIndex = 1
},
    
// Preset Strings2 
{
    .sound = {
        .type = SYNTH,
        .name = "Strings2",
        .synth = {
            .waveformType = 4,
            .amplitude = 0.78,
            .attack = 50,
            .decay = 400,
            .sustain = 0.6,
            .release = 308,
            .freqMod = 0.71,
            .phaseMod = 0.0,
            .ratioFm = 1.62,
            .modAmplitude = 0.19,
            .moogAttack = 161,
            .moogDecay = 400,
            .moogSustain = 0.8,
            .moogRelease = 411.76,
            .lpfResonance = 0.5,
            .octaveShift = 2,
            .lpfCutoff = 2367.06,
            .lpfEnvAmount = 0.57,
            .FMEnvAmount = 0.2,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = -1,
            .wavetable = 1
        }
    },

    .effects = {
        .reverbRoomSize = 0.0,
        .reverbDamping = 0.0,
        .filterFreq = 8532.35,
        .filterResonance = 0.0,
        .nChorus = 4,
        .tremoloWaveform = 7,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.08,
        .moogLfoWaveform = 7,
        .moogLfoRate = 0.0,
        .moogLfoAmplitude = 0.18,
        .noiseAmplitude = 0.1,
        .noiseCutoff = 3000.0,
        .noiseResonance = 0.8,
        .noiseEnvAttack = 100,
        .noiseEnvDecay = 300,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 200,
        .noiseCutoffEnvAmount = 3.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 2,
        .moogOctaveControl = 2,
        .moogCutoff = 1911.76,
        .moogResonance = 0.26,
    },

    .presetName = "Strings2 ",
    .soundTypeIndex = 2
},
    
// Preset Bell        
{
    .sound = {
        .type = SYNTH,
        .name = "Bell        ",
        .synth = {
            .waveformType = 0,
            .amplitude = 0.7,
            .attack = 1,
            .decay = 1000,
            .sustain = 0.2,
            .release = 1000,
            .freqMod = 0.5,
            .phaseMod = 1.0,
            .ratioFm = 3.5,
            .modAmplitude = 0.6,
            .moogAttack = 1,
            .moogDecay = 1000,
            .moogSustain = 0.1,
            .moogRelease = 794.12,
            .lpfResonance = 0.6,
            .octaveShift = 2,
            .lpfCutoff = 6000.0,
            .lpfEnvAmount = 1.5,
            .FMEnvAmount = 2.5,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = -1,
            .wavetable = 0,
        },
    },

    .effects = {
        .reverbRoomSize = 0.85,
        .reverbDamping = 0.5,
        .filterFreq = 8000.0,
        .filterResonance = 0.5,
        .nChorus = 2,
        .tremoloWaveform = 0,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = 0,
        .moogLfoRate = 0.1,
        .moogLfoAmplitude = 0.2,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 10,
        .noiseEnvDecay = 500,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 300,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 0,
        .moogCutoff = 2352.94,
        .moogResonance = 0.5,
    },

    .presetName = "Bell",
    .soundTypeIndex = 3
},
    
// Preset arcade race
{
    .sound = {
        .type = SYNTH,
        .name = "arcade race",
        .synth = {
            .waveformType = 2,
            .amplitude = 0.7,
            .attack = 5,
            .decay = 50,
            .sustain = 0.6,
            .release = 100,
            .freqMod = 1.0,
            .phaseMod = 0.0,
            .ratioFm = 0.5,
            .modAmplitude = 0.0,
            .moogAttack = 5,
            .moogDecay = 50,
            .moogSustain = 0.8,
            .moogRelease = 100.0,
            .lpfResonance = 1.0,
            .octaveShift = 2,
            .lpfCutoff = 489.41,
            .lpfEnvAmount = 3.0,
            .FMEnvAmount = 0.0,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = -1,
            .wavetable = 0,
        },
    },

    .effects = {
        .reverbRoomSize = 0.3,
        .reverbDamping = 0.8,
        .filterFreq = 800.0,
        .filterResonance = 5.0,
        .nChorus = 0,
        .tremoloWaveform = 0,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = 0,
        .moogLfoRate = 8.0,
        .moogLfoAmplitude = 0.49,
        .noiseAmplitude = 0.1,
        .noiseCutoff = 500.0,
        .noiseResonance = 1.0,
        .noiseEnvAttack = 10,
        .noiseEnvDecay = 200,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 100,
        .noiseCutoffEnvAmount = 3.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 2,
        .moogOctaveControl = 4,
        .moogCutoff = 6176.47,
        .moogResonance = 0.53,
    },

    .presetName = "arcade race",
    .soundTypeIndex = 4
},
    
// Preset E.Piano     
{
    .sound = {
        .type = SYNTH,
        .name = "E.Piano     ",
        .synth = {
            .waveformType = 0,
            .amplitude = 0.65,
            .attack = 8,
            .decay = 500,
            .sustain = 0.4,
            .release = 600,
            .freqMod = 1.0,
            .phaseMod = 1.0,
            .ratioFm = 2.0,
            .modAmplitude = 0.3,
            .moogAttack = 10,
            .moogDecay = 400,
            .moogSustain = 0.3,
            .moogRelease = 500.0,
            .lpfResonance = 0.9,
            .octaveShift = 2,
            .lpfCutoff = 2500.0,
            .lpfEnvAmount = 1.5,
            .FMEnvAmount = 1.0,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = -1,
            .wavetable = 0,
        },
    },

    .effects = {
        .reverbRoomSize = 0.6,
        .reverbDamping = 0.6,
        .filterFreq = 3500.0,
        .filterResonance = 1.0,
        .nChorus = 2,
        .tremoloWaveform = 0,
        .tremoloRate = 5.5,
        .tremoloAmplitude = 0.15,
        .moogLfoWaveform = 0,
        .moogLfoRate = 0.3,
        .moogLfoAmplitude = 0.25,
        .noiseAmplitude = 0.1,
        .noiseCutoff = 6617.65,
        .noiseResonance = 0.44,
        .noiseEnvAttack = 20,
        .noiseEnvDecay = 300,
        .noiseEnvSustain = 1.0,
        .noiseEnvRelease = 200,
        .noiseCutoffEnvAmount = 0.53,
        .noiseFilterType = 1,
        .noiseOctaveControl = 2,
        .moogOctaveControl = 2,
        .moogCutoff = 3500.0,
        .moogResonance = 0.6,
    },

    .presetName = "E.Piano",
    .soundTypeIndex = 5
},
   
// Preset Pad         
{
    .sound = {
        .type = SYNTH,
        .name = "Pad",
        .synth = {
            .waveformType = 0,
            .amplitude = 0.6,
            .attack = 500,
            .decay = 200,
            .sustain = 0.8,
            .release = 1000,
            .freqMod = 1.0,
            .phaseMod = 0.0,
            .ratioFm = 1.0,
            .modAmplitude = 0.0,
            .moogAttack = 500,
            .moogDecay = 200,
            .moogSustain = 0.7,
            .moogRelease = 800.0,
            .lpfResonance = 0.8,
            .octaveShift = 2,
            .lpfCutoff = 3000.0,
            .lpfEnvAmount = 1.0,
            .FMEnvAmount = 0.2,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = -1,
            .wavetable = 0,
        },
    },

    .effects = {
        .reverbRoomSize = 0.8,
        .reverbDamping = 0.5,
        .filterFreq = 1500.0,
        .filterResonance = 0.8,
        .nChorus = 3,
        .tremoloWaveform = 0,
        .tremoloRate = 2.0,
        .tremoloAmplitude = 0.1,
        .moogLfoWaveform = 0,
        .moogLfoRate = 0.3,
        .moogLfoAmplitude = 0.2,
        .noiseAmplitude = 0.1,
        .noiseCutoff = 2000.0,
        .noiseResonance = 0.7,
        .noiseEnvAttack = 100,
        .noiseEnvDecay = 400,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 300,
        .noiseCutoffEnvAmount = 3.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 2,
        .moogOctaveControl = 2,
        .moogCutoff = 1500.0,
        .moogResonance = 0.6,
    },

    .presetName = "Pad",
    .soundTypeIndex = 6
},
    
// Preset gamelan
{
    .sound = {
        .type = SYNTH,
        .name = "gamelan",
        .synth = {
            .waveformType = 0,
            .amplitude = 0.6,
            .attack = 10,
            .decay = 50,
            .sustain = 0.7,
            .release = 588,
            .freqMod = 0.6,
            .phaseMod = 1.0,
            .ratioFm = 0.75,
            .modAmplitude = 0.26,
            .moogAttack = 50,
            .moogDecay = 200,
            .moogSustain = 0.7,
            .moogRelease = 800.0,
            .lpfResonance = 0.8,
            .octaveShift = 3,
            .lpfCutoff = 4010.0,
            .lpfEnvAmount = 1.5,
            .FMEnvAmount = 1.0,
            .FMWaveform = 4,
            .lpfOctaveControl = 0,
            .FMwavetable = 8,
            .wavetable = 4,
        },
    },

    .effects = {
        .reverbRoomSize = 0.37,
        .reverbDamping = 0.12,
        .filterFreq = 3000.0,
        .filterResonance = 0.8,
        .nChorus = 8,
        .tremoloWaveform = 0,
        .tremoloRate = 0.74,
        .tremoloAmplitude = 0.1,
        .moogLfoWaveform = 0,
        .moogLfoRate = 0.3,
        .moogLfoAmplitude = 0.2,
        .noiseAmplitude = 0.1,
        .noiseCutoff = 2000.0,
        .noiseResonance = 0.7,
        .noiseEnvAttack = 100,
        .noiseEnvDecay = 400,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 300,
        .noiseCutoffEnvAmount = 0.71,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 2,
        .moogCutoff = 3000.0,
        .moogResonance = 0.6,
    },

    .presetName = "gamelan",
    .soundTypeIndex = 7
},
    
// Preset Square      
{
    .sound = {
        .type = SYNTH,
        .name = "Square",
        .synth = {
            .waveformType = 2,
            .amplitude = 0.7,
            .attack = 20,
            .decay = 50,
            .sustain = 0.4,
            .release = 200,
            .freqMod = 1.0,
            .phaseMod = 1.0,
            .ratioFm = 0.5,
            .modAmplitude = 0.25,
            .moogAttack = 50,
            .moogDecay = 200,
            .moogSustain = 0.7,
            .moogRelease = 800.0,
            .lpfResonance = 0.8,
            .octaveShift = 2,
            .lpfCutoff = 4000.0,
            .lpfEnvAmount = 1.5,
            .FMEnvAmount = 1.0,
            .FMWaveform = 2,
            .lpfOctaveControl = 0,
            .FMwavetable = 8,
            .wavetable = 4,
        },
    },

    .effects = {
        .reverbRoomSize = 0.12,
        .reverbDamping = 0.4,
        .filterFreq = 1000.0,
        .filterResonance = 0.8,
        .nChorus = 4,
        .tremoloWaveform = 0,
        .tremoloRate = 2.0,
        .tremoloAmplitude = 0.1,
        .moogLfoWaveform = 0,
        .moogLfoRate = 2.5,
        .moogLfoAmplitude = 0.32,
        .noiseAmplitude = 0.1,
        .noiseCutoff = 2000.0,
        .noiseResonance = 0.7,
        .noiseEnvAttack = 100,
        .noiseEnvDecay = 400,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 300,
        .noiseCutoffEnvAmount = 3.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 2,
        .moogOctaveControl = 1,
        .moogCutoff = 5000.0,
        .moogResonance = 0.15,
    },

    .presetName = "Square",
    .soundTypeIndex = 8
},
    
// Preset Mario       
{
    .sound = {
        .type = SYNTH,
        .name = "Mario",
        .synth = {
            .waveformType = 2,
            .amplitude = 0.8,
            .attack = 2,
            .decay = 80,
            .sustain = 0.0,
            .release = 30,
            .freqMod = 1.0,
            .phaseMod = 0.1,
            .ratioFm = 0.1,
            .modAmplitude = 0.1,
            .moogAttack = 0,
            .moogDecay = 0,
            .moogSustain = 0.0,
            .moogRelease = 0.0,
            .lpfResonance = 0.7,
            .octaveShift = 2,
            .lpfCutoff = 8000.0,
            .lpfEnvAmount = 0.0,
            .FMEnvAmount = 0.0,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = 8,
            .wavetable = 4,
        },
    },

    .effects = {
        .reverbRoomSize = 0.1,
        .reverbDamping = 0.7,
        .filterFreq = 3000.0,
        .filterResonance = 1.0,
        .nChorus = 0,
        .tremoloWaveform = 0,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = 0,
        .moogLfoRate = 0.0,
        .moogLfoAmplitude = 0.0,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 0,
        .moogCutoff = 3823.53,
        .moogResonance = 0.0,
    },

    .presetName = "Mario",
    .soundTypeIndex = 9
},
    
// Preset HandPan     
{
    .sound = {
        .type = SYNTH,
        .name = "HandPan",
        .synth = {
            .waveformType = 0,
            .amplitude = 0.6,
            .attack = 30,
            .decay = 1000,
            .sustain = 0.62,
            .release = 558,
            .freqMod = 0.68,
            .phaseMod = 0.0,
            .ratioFm = 1.62,
            .modAmplitude = 0.5,
            .moogAttack = 200,
            .moogDecay = 500,
            .moogSustain = 0.7,
            .moogRelease = 800.0,
            .lpfResonance = 0.8,
            .octaveShift = 2,
            .lpfCutoff = 2953.82,
            .lpfEnvAmount = 1.0,
            .FMEnvAmount = 0.3,
            .FMWaveform = 1,
            .lpfOctaveControl = 0,
            .FMwavetable = 8,
            .wavetable = 4,
        },
    },

    .effects = {
        .reverbRoomSize = 0.63,
        .reverbDamping = 0.5,
        .filterFreq = 3000.0,
        .filterResonance = 0.6,
        .nChorus = 8,
        .tremoloWaveform = 0,
        .tremoloRate = 1.18,
        .tremoloAmplitude = 0.1,
        .moogLfoWaveform = 0,
        .moogLfoRate = 0.74,
        .moogLfoAmplitude = 0.15,
        .noiseAmplitude = 0.1,
        .noiseCutoff = 2000.0,
        .noiseResonance = 0.7,
        .noiseEnvAttack = 100,
        .noiseEnvDecay = 400,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 300,
        .noiseCutoffEnvAmount = 3.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 2,
        .moogOctaveControl = 0,
        .moogCutoff = 3382.35,
        .moogResonance = 0.18,
    },

    .presetName = "HandPan",
    .soundTypeIndex = 10
},
    
// Preset 8-Bit
{
    .sound = {
        .type = SYNTH,
        .name = "8-Bit",
        .synth = {
            .waveformType = 2,
            .amplitude = 0.38,
            .attack = 5,
            .decay = 30,
            .sustain = 0.7,
            .release = 100,
            .freqMod = 1.0,
            .phaseMod = 0.0,
            .ratioFm = 2.0,
            .modAmplitude = 0.3,
            .moogAttack = 5,
            .moogDecay = 20,
            .moogSustain = 0.8,
            .moogRelease = 50.0,
            .lpfResonance = 0.2,
            .octaveShift = 2,
            .lpfCutoff = 3775.29,
            .lpfEnvAmount = 0.5,
            .FMEnvAmount = 0.5,
            .FMWaveform = 5,
            .lpfOctaveControl = 0,
            .FMwavetable = 2,
            .wavetable = 4,
        },
    },

    .effects = {
        .reverbRoomSize = 0.1,
        .reverbDamping = 0.9,
        .filterFreq = 4000.0,
        .filterResonance = 0.5,
        .nChorus = 2,
        .tremoloWaveform = 5,
        .tremoloRate = 8.0,
        .tremoloAmplitude = 0.2,
        .moogLfoWaveform = 7,
        .moogLfoRate = 0.0,
        .moogLfoAmplitude = 0.16,
        .noiseAmplitude = 0.1,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.09,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 1,
        .moogCutoff = 3235.29,
        .moogResonance = 0.12,
    },

    .presetName = "8-Bit",
    .soundTypeIndex = 11
},
   
// Preset droplet
{
    .sound = {
        .type = SYNTH,
        .name = "droplet",
        .synth = {
            .waveformType = 0,
            .amplitude = 1.0,
            .attack = 1,
            .decay = 150,
            .sustain = 0.0,
            .release = 50,
            .freqMod = 0.2,
            .phaseMod = 0.0,
            .ratioFm = 1.0,
            .modAmplitude = 0.8,
            .moogAttack = 1,
            .moogDecay = 100,
            .moogSustain = 0.0,
            .moogRelease = 20.0,
            .lpfResonance = 0.3,
            .octaveShift = 2,
            .lpfCutoff = 1000.0,
            .lpfEnvAmount = 2.0,
            .FMEnvAmount = 1.5,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = 2,
            .wavetable = 4,
        },
    },

    .effects = {
        .reverbRoomSize = 0.0,
        .reverbDamping = 1.0,
        .filterFreq = 200.0,
        .filterResonance = 0.8,
        .nChorus = 0,
        .tremoloWaveform = 0,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = 0,
        .moogLfoRate = 0.0,
        .moogLfoAmplitude = 0.0,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 0,
        .moogCutoff = 882.35,
        .moogResonance = 0.59,
    },

    .presetName = "droplet",
    .soundTypeIndex = 12
},
    
// Preset Synth bass
{
    .sound = {
        .type = SYNTH,
        .name = "Synth bass",
        .synth = {
            .waveformType = 5,
            .amplitude = 0.76,
            .attack = 2,
            .decay = 80,
            .sustain = 0.1,
            .release = 40,
            .freqMod = 1.0,
            .phaseMod = 0.0,
            .ratioFm = 3.0,
            .modAmplitude = 0.6,
            .moogAttack = 1,
            .moogDecay = 50,
            .moogSustain = 0.0,
            .moogRelease = 30.0,
            .lpfResonance = 0.6,
            .octaveShift = 0,
            .lpfCutoff = 2000.0,
            .lpfEnvAmount = 1.5,
            .FMEnvAmount = 1.0,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = 2,
            .wavetable = 4,
        },
    },

    .effects = {
        .reverbRoomSize = 0.2,
        .reverbDamping = 0.8,
        .filterFreq = 3000.0,
        .filterResonance = 1.5,
        .nChorus = 0,
        .tremoloWaveform = 0,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = 0,
        .moogLfoRate = 1.18,
        .moogLfoAmplitude = 0.59,
        .noiseAmplitude = 0.5,
        .noiseCutoff = 4000.0,
        .noiseResonance = 0.7,
        .noiseEnvAttack = 1,
        .noiseEnvDecay = 100,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 50,
        .noiseCutoffEnvAmount = 3.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 2,
        .moogOctaveControl = 0,
        .moogCutoff = 2205.88,
        .moogResonance = 0.15,
    },

    .presetName = "Synth bass",
    .soundTypeIndex = 13
},
   
// Preset Evolving Pad
{
    .sound = {
        .type = SYNTH,
        .name = "Evolving Pad",
        .synth = {
            .waveformType = 1,
            .amplitude = 0.5,
            .attack = 500,
            .decay = 200,
            .sustain = 0.8,
            .release = 800,
            .freqMod = 1.0,
            .phaseMod = 0.3,
            .ratioFm = 2.0,
            .modAmplitude = 0.4,
            .moogAttack = 300,
            .moogDecay = 400,
            .moogSustain = 0.6,
            .moogRelease = 600.0,
            .lpfResonance = 1.2,
            .octaveShift = 2,
            .lpfCutoff = 2500.0,
            .lpfEnvAmount = 1.5,
            .FMEnvAmount = 0.5,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = 2,
            .wavetable = 4,
        },
    },

    .effects = {
        .reverbRoomSize = 0.9,
        .reverbDamping = 0.4,
        .filterFreq = 800.0,
        .filterResonance = 2.0,
        .nChorus = 3,
        .tremoloWaveform = 0,
        .tremoloRate = 0.2,
        .tremoloAmplitude = 0.4,
        .moogLfoWaveform = 0,
        .moogLfoRate = 0.29,
        .moogLfoAmplitude = 0.63,
        .noiseAmplitude = 0.51,
        .noiseCutoff = 2352.94,
        .noiseResonance = 0.5,
        .noiseEnvAttack = 100,
        .noiseEnvDecay = 400,
        .noiseEnvSustain = 0.6,
        .noiseEnvRelease = 300,
        .noiseCutoffEnvAmount = 0.35,
        .noiseFilterType = 2,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 1,
        .moogCutoff = 800.0,
        .moogResonance = 0.6,
    },

    .presetName = "Evolving Pad",
    .soundTypeIndex = 14
},
   
// Preset FM Bass     
{
    .sound = {
        .type = SYNTH,
        .name = "FM Bass     ",
        .synth = {
            .waveformType = 4,
            .amplitude = 0.9,
            .attack = 5,
            .decay = 100,
            .sustain = 0.6,
            .release = 150,
            .freqMod = 1.0,
            .phaseMod = 0.0,
            .ratioFm = 4.0,
            .modAmplitude = 0.9,
            .moogAttack = 10,
            .moogDecay = 80,
            .moogSustain = 0.5,
            .moogRelease = 100.0,
            .lpfResonance = 1.5,
            .octaveShift = 1,
            .lpfCutoff = 500.0,
            .lpfEnvAmount = 3.0,
            .FMEnvAmount = 2.0,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = 2,
            .wavetable = 9,
        },
    },

    .effects = {
        .reverbRoomSize = 0.1,
        .reverbDamping = 0.9,
        .filterFreq = 400.0,
        .filterResonance = 2.5,
        .nChorus = 0,
        .tremoloWaveform = 0,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = 0,
        .moogLfoRate = 3.0,
        .moogLfoAmplitude = 0.5,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 0,
        .moogCutoff = 2941.18,
        .moogResonance = 0.0,
    },

    .presetName = "FM Bass",
    .soundTypeIndex = 15
},
   
// Preset Space Laser 
{
    .sound = {
        .type = SYNTH,
        .name = "Space Laser",
        .synth = {
            .waveformType = 1,
            .amplitude = 0.7,
            .attack = 1,
            .decay = 200,
            .sustain = 0.0,
            .release = 100,
            .freqMod = 0.1,
            .phaseMod = 0.5,
            .ratioFm = 5.0,
            .modAmplitude = 0.8,
            .moogAttack = 1,
            .moogDecay = 150,
            .moogSustain = 0.0,
            .moogRelease = 80.0,
            .lpfResonance = 2.0,
            .octaveShift = 2,
            .lpfCutoff = 4948.82,
            .lpfEnvAmount = 2.0,
            .FMEnvAmount = 1.5,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = 2,
            .wavetable = 9,
        },
    },

    .effects = {
        .reverbRoomSize = 0.7,
        .reverbDamping = 0.3,
        .filterFreq = 5000.0,
        .filterResonance = 3.0,
        .nChorus = 1,
        .tremoloWaveform = 0,
        .tremoloRate = 10.0,
        .tremoloAmplitude = 0.5,
        .moogLfoWaveform = 1,
        .moogLfoRate = 8.0,
        .moogLfoAmplitude = 0.7,
        .noiseAmplitude = 0.5,
        .noiseCutoff = 3382.35,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 132,
        .noiseEnvDecay = 191,
        .noiseEnvSustain = 0.57,
        .noiseEnvRelease = 176,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 1,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 0,
        .moogCutoff = 7647.06,
        .moogResonance = 0.59,
    },

    .presetName = "Space Laser",
    .soundTypeIndex = 16
},
   
// Preset Metal Bell  
{
    .sound = {
        .type = SYNTH,
        .name = "Metal Bell",
        .synth = {
            .waveformType = 0,
            .amplitude = 0.6,
            .attack = 2,
            .decay = 300,
            .sustain = 0.3,
            .release = 500,
            .freqMod = 1.0,
            .phaseMod = 0.0,
            .ratioFm = 7.0,
            .modAmplitude = 0.7,
            .moogAttack = 5,
            .moogDecay = 200,
            .moogSustain = 0.4,
            .moogRelease = 400.0,
            .lpfResonance = 0.4,
            .octaveShift = 2,
            .lpfCutoff = 4000.0,
            .lpfEnvAmount = 0.5,
            .FMEnvAmount = 0.0,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = 2,
            .wavetable = 9,
        },
    },

    .effects = {
        .reverbRoomSize = 0.8,
        .reverbDamping = 0.2,
        .filterFreq = 6000.0,
        .filterResonance = 1.0,
        .nChorus = 2,
        .tremoloWaveform = 0,
        .tremoloRate = 4.0,
        .tremoloAmplitude = 0.2,
        .moogLfoWaveform = 0,
        .moogLfoRate = 0.0,
        .moogLfoAmplitude = 0.0,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 0,
        .moogCutoff = 3088.24,
        .moogResonance = 0.0,
    },

    .presetName = "Metal Bell",
    .soundTypeIndex = 17
},
   
// Preset ...---...
{
    .sound = {
        .type = SYNTH,
        .name = "...---...",
        .synth = {
            .waveformType = 0,
            .amplitude = 0.47,
            .attack = 5,
            .decay = 50,
            .sustain = 0.3,
            .release = 50,
            .freqMod = 0.16,
            .phaseMod = 0.0,
            .ratioFm = 2.06,
            .modAmplitude = 0.4,
            .moogAttack = 5,
            .moogDecay = 30,
            .moogSustain = 0.5,
            .moogRelease = 40.0,
            .lpfResonance = 0.3,
            .octaveShift = 2,
            .lpfCutoff = 4000.0,
            .lpfEnvAmount = 0.5,
            .FMEnvAmount = 0.0,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = 9,
            .wavetable = 9,
        },
    },

    .effects = {
        .reverbRoomSize = 0.3,
        .reverbDamping = 0.8,
        .filterFreq = 3000.0,
        .filterResonance = 0.8,
        .nChorus = 2,
        .tremoloWaveform = 5,
        .tremoloRate = 10.0,
        .tremoloAmplitude = 0.57,
        .moogLfoWaveform = 5,
        .moogLfoRate = 5.0,
        .moogLfoAmplitude = 0.74,
        .noiseAmplitude = 0.18,
        .noiseCutoff = 8676.47,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 250,
        .noiseEnvDecay = 264,
        .noiseEnvSustain = 0.22,
        .noiseEnvRelease = 617,
        .noiseCutoffEnvAmount = 0.35,
        .noiseFilterType = 2,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 1,
        .moogCutoff = 6323.53,
        .moogResonance = 0.0,
    },

    .presetName = "...---...",
    .soundTypeIndex = 18
},
   
// Preset lead
{
    .sound = {
        .type = SYNTH,
        .name = "lead",
        .synth = {
            .waveformType = 4,
            .amplitude = 0.5,
            .attack = 1,
            .decay = 40,
            .sustain = 0.0,
            .release = 44,
            .freqMod = 0.5,
            .phaseMod = 0.0,
            .ratioFm = 5.44,
            .modAmplitude = 1.0,
            .moogAttack = 1,
            .moogDecay = 30,
            .moogSustain = 0.0,
            .moogRelease = 15.0,
            .lpfResonance = 0.5,
            .octaveShift = 1,
            .lpfCutoff = 6000.0,
            .lpfEnvAmount = 1.0,
            .FMEnvAmount = 0.0,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = 13,
            .wavetable = 12,
        },
    },

    .effects = {
        .reverbRoomSize = 0.1,
        .reverbDamping = 0.9,
        .filterFreq = 8000.0,
        .filterResonance = 1.8,
        .nChorus = 0,
        .tremoloWaveform = 0,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = 0,
        .moogLfoRate = 0.0,
        .moogLfoAmplitude = 0.0,
        .noiseAmplitude = 0.09,
        .noiseCutoff = 1911.76,
        .noiseResonance = 0.6,
        .noiseEnvAttack = 1,
        .noiseEnvDecay = 50,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 20,
        .noiseCutoffEnvAmount = 0.88,
        .noiseFilterType = 1,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 0,
        .moogCutoff = 6470.59,
        .moogResonance = 0.26,
    },

    .presetName = "lead",
    .soundTypeIndex = 19
},
    
   
// Preset Electric Org
{
    .sound = {
        .type = SYNTH,
        .name = "Elec Organ",
        .synth = {
            .waveformType = 0,
            .amplitude = 0.6,
            .attack = 10,
            .decay = 20,
            .sustain = 0.9,
            .release = 100,
            .freqMod = 1.0,
            .phaseMod = 0.0,
            .ratioFm = 2.0,
            .modAmplitude = 0.3,
            .moogAttack = 20,
            .moogDecay = 30,
            .moogSustain = 0.8,
            .moogRelease = 80.0,
            .lpfResonance = 0.6,
            .octaveShift = 2,
            .lpfCutoff = 3000.0,
            .lpfEnvAmount = 1.0,
            .FMEnvAmount = 0.5,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = 9,
            .wavetable = 9,
        },
    },

    .effects = {
        .reverbRoomSize = 0.4,
        .reverbDamping = 0.6,
        .filterFreq = 2500.0,
        .filterResonance = 1.0,
        .nChorus = 3,
        .tremoloWaveform = 0,
        .tremoloRate = 6.0,
        .tremoloAmplitude = 0.4,
        .moogLfoWaveform = 0,
        .moogLfoRate = 0.3,
        .moogLfoAmplitude = 0.3,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 0,
        .moogCutoff = 5882.35,
        .moogResonance = 0.0,
    },

    .presetName = "Elec Organ",
    .soundTypeIndex = 20
},
    
// Preset Glitch      
{
    .sound = {
        .type = SYNTH,
        .name = "Glitch",
        .synth = {
            .waveformType = 2,
            .amplitude = 0.7,
            .attack = 1,
            .decay = 30,
            .sustain = 0.07,
            .release = 50,
            .freqMod = 1.0,
            .phaseMod = 0.8,
            .ratioFm = 10.0,
            .modAmplitude = 0.47,
            .moogAttack = 117,
            .moogDecay = 88,
            .moogSustain = 0.6,
            .moogRelease = 88.24,
            .lpfResonance = 3.0,
            .octaveShift = 2,
            .lpfCutoff = 4244.71,
            .lpfEnvAmount = 0.79,
            .FMEnvAmount = 0.93,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = 13,
            .wavetable = 15,
        },
    },

    .effects = {
        .reverbRoomSize = 0.3,
        .reverbDamping = 0.5,
        .filterFreq = 4863.24,
        .filterResonance = 3.16,
        .nChorus = 1,
        .tremoloWaveform = 7,
        .tremoloRate = 10.0,
        .tremoloAmplitude = 0.19,
        .moogLfoWaveform = 7,
        .moogLfoRate = 10.0,
        .moogLfoAmplitude = 0.9,
        .noiseAmplitude = 0.54,
        .noiseCutoff = 2647.06,
        .noiseResonance = 0.21,
        .noiseEnvAttack = 58,
        .noiseEnvDecay = 308,
        .noiseEnvSustain = 0.49,
        .noiseEnvRelease = 20,
        .noiseCutoffEnvAmount = 3.0,
        .noiseFilterType = 1,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 0,
        .moogCutoff = 3235.29,
        .moogResonance = 0.24,
    },

    .presetName = "Glitch",
    .soundTypeIndex = 21
    
},
    
// Preset Accordeon
{
    .sound = {
        .type = SYNTH,
        .name = "Accordeon",
        .synth = {
            .waveformType = 4,
            .amplitude = 0.8,
            .attack = 50,
            .decay = 100,
            .sustain = 0.8,
            .release = 150,
            .freqMod = 1.0,
            .phaseMod = 0.0,
            .ratioFm = 1.0,
            .modAmplitude = 0.0,
            .moogAttack = 100,
            .moogDecay = 200,
            .moogSustain = 0.9,
            .moogRelease = 150.0,
            .lpfResonance = 0.5,
            .octaveShift = 3,
            .lpfCutoff = 4000.0,
            .lpfEnvAmount = 1.0,
            .FMEnvAmount = 0.0,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = 9,
            .wavetable = 1
        }
    },

    .effects = {
        .reverbRoomSize = 1.0,
        .reverbDamping = 1.0,
        .filterFreq = 10000.0,
        .filterResonance = 4.19,
        .nChorus = 2,
        .tremoloWaveform = 0,
        .tremoloRate = 3.82,
        .tremoloAmplitude = 0.6,
        .moogLfoWaveform = 0,
        .moogLfoRate = 2.65,
        .moogLfoAmplitude = 0.44,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 1,
        .moogCutoff = 8529.41,
        .moogResonance = 0.5,
    },

    .presetName = "Accordeon",
    .soundTypeIndex = 22
},
    
// Preset loco
{
    .sound = {
        .type = SYNTH,
        .name = "loco",
        .synth = {
            .waveformType = 4,
            .amplitude = 0.8,
            .attack = 426,
            .decay = 100,
            .sustain = 0.8,
            .release = 397,
            .freqMod = 0.46,
            .phaseMod = 0.49,
            .ratioFm = 1.47,
            .modAmplitude = 0.72,
            .moogAttack = 100,
            .moogDecay = 200,
            .moogSustain = 0.9,
            .moogRelease = 441.18,
            .lpfResonance = 0.5,
            .octaveShift = 2,
            .lpfCutoff = 1428.24,
            .lpfEnvAmount = 1.0,
            .FMEnvAmount = 0.75,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = 13,
            .wavetable = 15,
        },
    },

    .effects = {
        .reverbRoomSize = 0.4,
        .reverbDamping = 0.43,
        .filterFreq = 4276.18,
        .filterResonance = 1.5,
        .nChorus = 0,
        .tremoloWaveform = 5,
        .tremoloRate = 2.0,
        .tremoloAmplitude = 0.6,
        .moogLfoWaveform = 5,
        .moogLfoRate = 1.5,
        .moogLfoAmplitude = 0.72,
        .noiseAmplitude = 1.0,
        .noiseCutoff = 1323.53,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 117,
        .noiseEnvDecay = 279,
        .noiseEnvSustain = 0.65,
        .noiseEnvRelease = 867,
        .noiseCutoffEnvAmount = 0.49,
        .noiseFilterType = 2,
        .noiseOctaveControl = 1,
        .moogOctaveControl = 0,
        .moogCutoff = 735.29,
        .moogResonance = 0.0,
    },

    .presetName = "loco",
    .soundTypeIndex = 23
},
    
// Preset Wobble Bass 
{
    .sound = {
        .type = SYNTH,
        .name = "Wobble Bass ",
        .synth = {
            .waveformType = 1,
            .amplitude = 0.9,
            .attack = 10,
            .decay = 50,
            .sustain = 0.8,
            .release = 100,
            .freqMod = 1.0,
            .phaseMod = 0.0,
            .ratioFm = 1.0,
            .modAmplitude = 0.0,
            .moogAttack = 5,
            .moogDecay = 30,
            .moogSustain = 0.9,
            .moogRelease = 50.0,
            .lpfResonance = 4.0,
            .octaveShift = 0,
            .lpfCutoff = 600.0,
            .lpfEnvAmount = 3.0,
            .FMEnvAmount = 0.0,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = 9,
            .wavetable = 9,
        },
    },

    .effects = {
        .reverbRoomSize = 0.2,
        .reverbDamping = 0.8,
        .filterFreq = 500.0,
        .filterResonance = 5.0,
        .nChorus = 0,
        .tremoloWaveform = 0,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = 0,
        .moogLfoRate = 6.0,
        .moogLfoAmplitude = 0.57,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 0,
        .moogCutoff = 1617.65,
        .moogResonance = 0.21,
    },

    .presetName = "Wobble Bass ",
    .soundTypeIndex = 24
},
    
// Preset Ambient
{
    .sound = {
        .type = SYNTH,
        .name = "Ambient",
        .synth = {
            .waveformType = 1,
            .amplitude = 0.4,
            .attack = 1000,
            .decay = 500,
            .sustain = 0.9,
            .release = 1000,
            .freqMod = 1.0,
            .phaseMod = 0.2,
            .ratioFm = 3.0,
            .modAmplitude = 0.3,
            .moogAttack = 800,
            .moogDecay = 600,
            .moogSustain = 0.8,
            .moogRelease = 1000.0,
            .lpfResonance = 1.5,
            .octaveShift = 2,
            .lpfCutoff = 2000.0,
            .lpfEnvAmount = 2.0,
            .FMEnvAmount = 0.5,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = 13,
            .wavetable = 15,
        },
    },

    .effects = {
        .reverbRoomSize = 1.0,
        .reverbDamping = 0.3,
        .filterFreq = 600.0,
        .filterResonance = 2.5,
        .nChorus = 3,
        .tremoloWaveform = 0,
        .tremoloRate = 0.1,
        .tremoloAmplitude = 0.3,
        .moogLfoWaveform = 0,
        .moogLfoRate = 0.05,
        .moogLfoAmplitude = 0.7,
        .noiseAmplitude = 0.25,
        .noiseCutoff = 1500.0,
        .noiseResonance = 0.5,
        .noiseEnvAttack = 500,
        .noiseEnvDecay = 800,
        .noiseEnvSustain = 0.2,
        .noiseEnvRelease = 1000,
        .noiseCutoffEnvAmount = 3.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 1,
        .moogOctaveControl = 2,
        .moogCutoff = 800.0,
        .moogResonance = 0.6,
    },

    .presetName = "Ambient",
    .soundTypeIndex = 25
    
},
    
// Preset tuk
{
    .sound = {
        .type = SYNTH,
        .name = "tuk",
        .synth = {
            .waveformType = 2,
            .amplitude = 1.0,
            .attack = 1,
            .decay = 300,
            .sustain = 0.0,
            .release = 200,
            .freqMod = 0.1,
            .phaseMod = 0.0,
            .ratioFm = 1.0,
            .modAmplitude = 0.5,
            .moogAttack = 1,
            .moogDecay = 250,
            .moogSustain = 0.0,
            .moogRelease = 150.0,
            .lpfResonance = 0.8,
            .octaveShift = 2,
            .lpfCutoff = 1000.0,
            .lpfEnvAmount = 3.0,
            .FMEnvAmount = 0.0,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = 13,
            .wavetable = 15,
        },
    },

    .effects = {
        .reverbRoomSize = 0.35,
        .reverbDamping = 0.56,
        .filterFreq = 800.0,
        .filterResonance = 1.2,
        .nChorus = 0,
        .tremoloWaveform = 0,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = 0,
        .moogLfoRate = 0.0,
        .moogLfoAmplitude = 0.0,
        .noiseAmplitude = 0.5,
        .noiseCutoff = 4852.94,
        .noiseResonance = 1.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 58,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 1.5,
        .noiseFilterType = 2,
        .noiseOctaveControl = 2,
        .moogOctaveControl = 0,
        .moogCutoff = 882.35,
        .moogResonance = 0.0,
    },

    .presetName = "tuk",
    .soundTypeIndex = 26

},
    
// Preset Electric Plu
{
    .sound = {
        .type = SYNTH,
        .name = "Elec Pluck",
        .synth = {
            .waveformType = 1,
            .amplitude = 0.8,
            .attack = 5,
            .decay = 150,
            .sustain = 0.2,
            .release = 44,
            .freqMod = 0.41,
            .phaseMod = 0.99,
            .ratioFm = 3.0,
            .modAmplitude = 0.6,
            .moogAttack = 1,
            .moogDecay = 100,
            .moogSustain = 0.1,
            .moogRelease = 80.0,
            .lpfResonance = 1.8,
            .octaveShift = 2,
            .lpfCutoff = 3000.0,
            .lpfEnvAmount = 3.0,
            .FMEnvAmount = 1.0,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = 13,
            .wavetable = 15,
        },
    },

    .effects = {
        .reverbRoomSize = 0.3,
        .reverbDamping = 0.13,
        .filterFreq = 3500.0,
        .filterResonance = 0.29,
        .nChorus = 2,
        .tremoloWaveform = 0,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = 0,
        .moogLfoRate = 0.74,
        .moogLfoAmplitude = 0.5,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 0,
        .moogCutoff = 4411.76,
        .moogResonance = 0.0,
    },

    .presetName = "Elec Pluck",
    .soundTypeIndex = 27
},
    
// Preset baleine
{
    .sound = {
        .type = SYNTH,
        .name = "baleine",
        .synth = {
            .waveformType = 3,
            .amplitude = 0.5,
            .attack = 800,
            .decay = 400,
            .sustain = 0.7,
            .release = 1000,
            .freqMod = 1.0,
            .phaseMod = 0.1,
            .ratioFm = 1.0,
            .modAmplitude = 0.2,
            .moogAttack = 600,
            .moogDecay = 500,
            .moogSustain = 0.6,
            .moogRelease = 900.0,
            .lpfResonance = 0.8,
            .octaveShift = 2,
            .lpfCutoff = 1500.0,
            .lpfEnvAmount = 2.0,
            .FMEnvAmount = 0.3,
            .FMWaveform = 0,
            .lpfOctaveControl = 0,
            .FMwavetable = 13,
            .wavetable = 15,
        },
    },

    .effects = {
        .reverbRoomSize = 0.9,
        .reverbDamping = 0.5,
        .filterFreq = 1200.0,
        .filterResonance = 1.5,
        .nChorus = 2,
        .tremoloWaveform = 0,
        .tremoloRate = 0.3,
        .tremoloAmplitude = 0.5,
        .moogLfoWaveform = 0,
        .moogLfoRate = 0.2,
        .moogLfoAmplitude = 0.8,
        .noiseAmplitude = 0.28,
        .noiseCutoff = 1000.0,
        .noiseResonance = 0.5,
        .noiseEnvAttack = 500,
        .noiseEnvDecay = 600,
        .noiseEnvSustain = 0.3,
        .noiseEnvRelease = 800,
        .noiseCutoffEnvAmount = 3.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 2,
        .moogOctaveControl = 2,
        .moogCutoff = 700.0,
        .moogResonance = 0.6,
    },

    .presetName = "baleine",
    .soundTypeIndex = 28
},
{   
    .sound = {
        .type = STRING,
        .name = "Pluck",
        .string = {
            .velocity = 0.65,
            .moogAttack = 20,
            .moogDecay = 50,
            .moogSustain = 0.7,
            .moogRelease = 0.0,
            .octaveShift = 2,
        },
    },

    .effects = {
        .reverbRoomSize = 0.1,
        .reverbDamping = 0.18,
        .filterFreq = 3835.88,
        .filterResonance = 0.0,
        .nChorus = 4,
        .tremoloWaveform = 25,
        .tremoloRate = 0.29,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = 1,
        .moogLfoRate = 0.0,
        .moogLfoAmplitude = 0.0,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 2647.06,
        .noiseResonance = 0.53,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 323,
        .noiseCutoffEnvAmount = 1.24,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 4,
        .moogCutoff = 4264.71,
        .moogResonance = 0.18,
    },

    .presetName = "Pluck",
    .soundTypeIndex = 29
        

    },
    // Preset 30 : Boom
    {   
        .sound = {
        .type = DRUM,
        .name = "Boom",
        .drum = {
            .length = 691,
            .secondMix = 0.8,
            .pitchMod = 0.87,
            .moogAttack = 20,
            .moogDecay = 308,
            .moogSustain = 0.7,
            .moogRelease = 294.12,
            .octaveShift = 1,
        },
    },

    .effects = {
        .reverbRoomSize = 0.0,
        .reverbDamping = 0.0,
        .filterFreq = 20.0,
        .filterResonance = 0.0,
        .nChorus = 1,
        .tremoloWaveform = 25,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = 1,
        .moogLfoRate = 0.0,
        .moogLfoAmplitude = 0.0,
        .noiseAmplitude = 0.46,
        .noiseCutoff = 6176.47,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 73,
        .noiseEnvDecay = 63,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 2,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 0,
        .moogCutoff = 7352.94,
        .moogResonance = 0.0,
    },

    .presetName = "Boom",
    .soundTypeIndex = 30

    },
    // Preset 31 : drums
    {   
        .sound = {
        .type = SAMPLE,
        .name = "Drums",
        .sample = {
            .moogAttack = 20,
            .moogDecay = 30,
            .moogSustain = 0.7,
            .moogRelease = 0.0,
            .drumKitId = 0
        },
    },

    .effects = {
        .reverbRoomSize = 0.24,
        .reverbDamping = 0.09,
        .filterFreq = 5303.53,
        .filterResonance = 2.72,
        .nChorus = 1,
        .tremoloWaveform = 0,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = 0,
        .moogLfoRate = 0.0,
        .moogLfoAmplitude = 0.0,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 0,
        .moogCutoff = 8235.29,
        .moogResonance = 0.0,
    },

    .presetName = "Drums",
    .soundTypeIndex = 31

    },
    {   
        .sound = {
        .type = SAMPLE,
        .name = "Percus",
        .sample = {
            .moogAttack = 20,
            .moogDecay = 30,
            .moogSustain = 0.7,
            .moogRelease = 0.0,
            .drumKitId = 1
        },
    },

    .effects = {
        .reverbRoomSize = 0.1,
        .reverbDamping = 0.4,
        .filterFreq = 5303.53,
        .filterResonance = 2.72,
        .nChorus = 1,
        .tremoloWaveform = 0,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = 0,
        .moogLfoRate = 0.0,
        .moogLfoAmplitude = 0.0,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 0,
        .moogCutoff = 8235.29,
        .moogResonance = 0.0,
    },

    .presetName = "Percus",
    .soundTypeIndex = 32

    },
    {   
        .sound = {
        .type = SAMPLE,
        .name = "Gamelan",
        .sample = {
            .moogAttack = 20,
            .moogDecay = 30,
            .moogSustain = 0.7,
            .moogRelease = 0.0,
            .drumKitId = 2
        },
    },

    .effects = {
        .reverbRoomSize = 0.24,
        .reverbDamping = 0.2,
        .filterFreq = 5303.53,
        .filterResonance = 2.72,
        .nChorus = 1,
        .tremoloWaveform = 0,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = 0,
        .moogLfoRate = 0.0,
        .moogLfoAmplitude = 0.0,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0,
        .moogOctaveControl = 0,
        .moogCutoff = 8235.29,
        .moogResonance = 0.0,
    },

    .presetName = "Gamelan",
    .soundTypeIndex = 33

    }


};

inline const Preset& getPreset(int index) {
    return DEFAULT_PRESETS[index % NUM_PRESETS];  // Modulo = toujours valide
}
