#include "Presets.h"

// ========== PRESETS PRÉDÉFINIS ==========
const Preset DEFAULT_PRESETS[NUM_PRESETS] = {
    // Preset 0 : Lead Synth
    {
        .sound = {
            .type = SYNTH,
            .name = "Lead Synth",
            .synth = {
                .waveformType = WAVEFORM_SAWTOOTH,
                .amplitude = 0.7,
                .attack = 10,
                .decay = 50,
                .sustain = 0.5,
                .release = 200,
                .freqMod = 1.0,
                .phaseMod = 0.0,
                .ratioFm = 1,
                .modAmplitude = 0.0,
                .moogAttack = 10,
                .moogDecay = 50,
                .moogSustain = 0.6,
                .moogRelease = 100,
                .lpfResonance = 0.8,
                .octaveShift = 2,
                .lpfCutoff = 5000.0,
                .lpfEnvAmount = 0.5,
                .FMEnvAmount = 0.5,
                .FMWaveform = WAVEFORM_SINE,
                .lpfOctaveControl = 2.0
            }
        },
        .effects = {
            .reverbRoomSize = 0.5,
            .reverbDamping = 0.7,
            .filterFreq = 2000.0,
            .filterResonance = 1.2,
            .nChorus = 2,
            .tremoloWaveform = WAVEFORM_SINE,
            .tremoloRate = 5.0,
            .tremoloAmplitude = 0.3,
            .moogLfoWaveform = WAVEFORM_SINE,
            .moogLfoRate = 0.5,
            .moogLfoAmplitude = 0.4,
            .noiseAmplitude = 0.2,
            .noiseCutoff = 5000.0,
            .noiseResonance = 1.0,
            .noiseEnvAttack = 50,
            .noiseEnvDecay = 200,
            .noiseEnvSustain = 0.0,
            .noiseEnvRelease = 100,
            .noiseCutoffEnvAmount = 3000.0,
            .noiseFilterType = 0,
            .noiseOctaveControl = 2.0,
            .moogOctaveControl = 2.0,
            .moogCutoff = 5000.0,
            .moogResonance = 0.7
        },
        .presetName = "Lead Synth",
        .soundTypeIndex = 0
    },
    // Preset 1 : Deep Bass
    {
        .sound = {
            .type = SYNTH,
            .name = "Deep Bass",
            .synth = {
                .waveformType = WAVEFORM_SINE,
                .amplitude = 0.7,
                .attack = 5,
                .decay = 100,
                .sustain = 0.5,
                .release = 300,
                .freqMod = 2.0,
                .phaseMod = 0.0,
                .ratioFm = 0.5,
                .modAmplitude = 0.4,
                .moogAttack = 5,
                .moogDecay = 80,
                .moogSustain = 0.8,
                .moogRelease = 200,
                .lpfResonance = 0.7,
                .octaveShift = 2,
                .lpfCutoff = 300.0,
                .lpfEnvAmount = 2.0,
                .FMEnvAmount = 1.5,
                .FMWaveform = WAVEFORM_SINE,
                .lpfOctaveControl = 3.0
            }
        },
        .effects = {
            .reverbRoomSize = 0.2,
            .reverbDamping = 0.9,
            .filterFreq = 400.0,
            .filterResonance = 2.5,
            .nChorus = 0,
            .tremoloWaveform = WAVEFORM_SINE,
            .tremoloRate = 3.0,
            .tremoloAmplitude = 0.6,
            .moogLfoWaveform = WAVEFORM_SINE,
            .moogLfoRate = 3,
            .moogLfoAmplitude = 0.6,
            .noiseAmplitude = 0.1,
            .noiseCutoff = 200.0,
            .noiseResonance = 1.5,
            .noiseEnvAttack = 20,
            .noiseEnvDecay = 100,
            .noiseEnvSustain = 0.0,
            .noiseEnvRelease = 100,
            .noiseCutoffEnvAmount = 1000.0,
            .noiseFilterType = 0,
            .noiseOctaveControl = 3.0,
            .moogOctaveControl = 3.0,
            .moogCutoff = 400.0,
            .moogResonance = 0.8
        },
        .presetName = "Deep Bass",
        .soundTypeIndex = 1
    },
    
    // Preset 2 : Strings Pad
    {
        .sound = {
            .type = SYNTH,
            .name = "Strings",
            .synth = {
                .waveformType = WAVEFORM_SAWTOOTH,
                .amplitude = 0.5,
                .attack = 500,
                .decay = 400,
                .sustain = 0.6,
                .release = 1000,
                .freqMod = 1.0,
                .phaseMod = 0.0,
                .ratioFm = 1.01,
                .modAmplitude = 0.05,
                .moogAttack = 800,
                .moogDecay = 400,
                .moogSustain = 0.8,
                .moogRelease = 1200,
                .lpfResonance = 0.5,
                .octaveShift = 2,
                .lpfCutoff = 4000.0,
                .lpfEnvAmount = 1.0,
                .FMEnvAmount = 0.2,
                .FMWaveform = WAVEFORM_SINE,
                .lpfOctaveControl = 2.5
            }
        },
        .effects = {
            .reverbRoomSize = 0.85,
            .reverbDamping = 0.4,
            .filterFreq = 2500.0,
            .filterResonance = 0.7,
            .nChorus = 4,
            .tremoloWaveform = WAVEFORM_SINE,
            .tremoloRate = 4.5,
            .tremoloAmplitude = 0.08,
            .moogLfoWaveform = WAVEFORM_SINE,
            .moogLfoRate = 0.2,
            .moogLfoAmplitude = 0.3,
            .noiseAmplitude = 0.1,
            .noiseCutoff = 3000.0,
            .noiseResonance = 0.8,
            .noiseEnvAttack = 100,
            .noiseEnvDecay = 300,
            .noiseEnvSustain = 0.0,
            .noiseEnvRelease = 200,
            .noiseCutoffEnvAmount = 2000.0,
            .noiseFilterType = 0,
            .noiseOctaveControl = 2.0,
            .moogOctaveControl = 2.0,
            .moogCutoff = 4000.0,
            .moogResonance = 0.6
        },
        .presetName = "Strings",
        .soundTypeIndex = 2
    },
    
    // Preset 3 : Bell/Chime
    {
        .sound = {
            .type = SYNTH,
            .name = "Bell",
            .synth = {
                .waveformType = WAVEFORM_SINE,
                .amplitude = 0.7,
                .attack = 1,
                .decay = 2000,
                .sustain = 0.2,
                .release = 1000,
                .freqMod = 0.5,
                .phaseMod = 180,
                .ratioFm = 3.5,
                .modAmplitude = 0.6,
                .moogAttack = 1,
                .moogDecay = 1000,
                .moogSustain = 0.1,
                .moogRelease = 1000,
                .lpfResonance = 0.6,
                .octaveShift = 2,
                .lpfCutoff = 6000.0,
                .lpfEnvAmount = 1.5,
                .FMEnvAmount = 2.5,
                .FMWaveform = WAVEFORM_SINE,
                .lpfOctaveControl = 2.0
            }
        },
        .effects = {
            .reverbRoomSize = 0.85,
            .reverbDamping = 0.5,
            .filterFreq = 8000.0,
            .filterResonance = 0.5,
            .nChorus = 2,
            .tremoloWaveform = WAVEFORM_SINE,
            .tremoloRate = 0.0,
            .tremoloAmplitude = 0.0,
            .moogLfoWaveform = WAVEFORM_SINE,
            .moogLfoRate = 0.1,
            .moogLfoAmplitude = 0.2,
            .noiseAmplitude = 0.0,
            .noiseCutoff = 0.0,
            .noiseResonance = 0.0,
            .noiseEnvAttack = 10,
            .noiseEnvDecay = 500,
            .noiseEnvSustain = 0.0,
            .noiseEnvRelease = 300,
            .noiseCutoffEnvAmount = 0.0,
            .noiseFilterType = 0,
            .noiseOctaveControl = 0.0,
            .moogOctaveControl = 0.0,
            .moogCutoff = 1000.0,
            .moogResonance = 0.5
        },
        .presetName = "Bell",
        .soundTypeIndex = 3
    },
    
    // Preset 4 : Wobble Bass
    {
        .sound = {
            .type = SYNTH,
            .name = "Wobble",
            .synth = {
                .waveformType = WAVEFORM_SQUARE,
                .amplitude = 0.7,
                .attack = 5,
                .decay = 50,
                .sustain = 0.6,
                .release = 100,
                .freqMod = 1.0,
                .phaseMod = 0.0,
                .ratioFm = 0.5,
                .modAmplitude = 0.0,
                .moogAttack = 5,
                .moogDecay = 50,
                .moogSustain = 0.8,
                .moogRelease = 100,
                .lpfResonance = 1.0,
                .octaveShift = 2,
                .lpfCutoff = 200.0,
                .lpfEnvAmount = 3.0,
                .FMEnvAmount = 0.0,
                .FMWaveform = WAVEFORM_SINE,
                .lpfOctaveControl = 4.0
            }
        },
        .effects = {
            .reverbRoomSize = 0.3,
            .reverbDamping = 0.8,
            .filterFreq = 800.0,
            .filterResonance = 5.0,
            .nChorus = 0,
            .tremoloWaveform = WAVEFORM_SINE,
            .tremoloRate = 0.0,
            .tremoloAmplitude = 0.0,
            .moogLfoWaveform = WAVEFORM_SINE,
            .moogLfoRate = 8.0,
            .moogLfoAmplitude = 1.0,
            .noiseAmplitude = 0.1,
            .noiseCutoff = 500.0,
            .noiseResonance = 1.0,
            .noiseEnvAttack = 10,
            .noiseEnvDecay = 200,
            .noiseEnvSustain = 0.0,
            .noiseEnvRelease = 100,
            .noiseCutoffEnvAmount = 1500.0,
            .noiseFilterType = 0,
            .noiseOctaveControl = 3.0,
            .moogOctaveControl = 4.0,
            .moogCutoff = 800.0,
            .moogResonance = 1.0
        },
        .presetName = "Wobble",
        .soundTypeIndex = 4
    },
    
    // Preset 5 : Electric Piano
    {
        .sound = {
            .type = SYNTH,
            .name = "E.Piano",
            .synth = {
                .waveformType = WAVEFORM_SINE,
                .amplitude = 0.65,
                .attack = 8,
                .decay = 500,
                .sustain = 0.4,
                .release = 600,
                .freqMod = 1.0,
                .phaseMod = 45,
                .ratioFm = 2.0,
                .modAmplitude = 0.3,
                .moogAttack = 10,
                .moogDecay = 400,
                .moogSustain = 0.3,
                .moogRelease = 500,
                .lpfResonance = 0.9,
                .octaveShift = 2,
                .lpfCutoff = 2500.0,
                .lpfEnvAmount = 1.5,
                .FMEnvAmount = 1.0,
                .FMWaveform = WAVEFORM_SINE,
                .lpfOctaveControl = 2.5
            }
        },
        .effects = {
            .reverbRoomSize = 0.6,
            .reverbDamping = 0.6,
            .filterFreq = 3500.0,
            .filterResonance = 1.0,
            .nChorus = 2,
            .tremoloWaveform = WAVEFORM_SINE,
            .tremoloRate = 5.5,
            .tremoloAmplitude = 0.15,
            .moogLfoWaveform = WAVEFORM_SINE,
            .moogLfoRate = 0.3,
            .moogLfoAmplitude = 0.25,
            .noiseAmplitude = 0.05,
            .noiseCutoff = 4000.0,
            .noiseResonance = 0.7,
            .noiseEnvAttack = 20,
            .noiseEnvDecay = 300,
            .noiseEnvSustain = 0.0,
            .noiseEnvRelease = 200,
            .noiseCutoffEnvAmount = 1500.0,
            .noiseFilterType = 0,
            .noiseOctaveControl = 2.0,
            .moogOctaveControl = 2.0,
            .moogCutoff = 3500.0,
            .moogResonance = 0.6
        },
        .presetName = "E.Piano",
        .soundTypeIndex = 5
    },
    // Preset 6 : Pad
    {
        .sound = {
            .type = SYNTH,
            .name = "Pad",
            .synth = {
                .waveformType = WAVEFORM_SINE,
                .amplitude = 0.6,
                .attack = 500,
                .decay = 200,
                .sustain = 0.8,
                .release = 1000,
                .freqMod = 1.0,
                .phaseMod = 0.0,
                .ratioFm = 1.0,
                .modAmplitude = 0.0,
                .moogAttack = 500,
                .moogDecay = 200,
                .moogSustain = 0.7,
                .moogRelease = 800,
                .lpfResonance = 0.8,
                .octaveShift = 2,
                .lpfCutoff = 3000.0,
                .lpfEnvAmount = 1.0,
                .FMEnvAmount = 0.2,
                .FMWaveform = WAVEFORM_SINE,
                .lpfOctaveControl = 2.0
            }
        },
        .effects = {
            .reverbRoomSize = 0.8,
            .reverbDamping = 0.5,
            .filterFreq = 1500.0,
            .filterResonance = 0.8,
            .nChorus = 3,
            .tremoloWaveform = WAVEFORM_SINE,
            .tremoloRate = 2.0,
            .tremoloAmplitude = 0.1,
            .moogLfoWaveform = WAVEFORM_SINE,
            .moogLfoRate = 0.3,
            .moogLfoAmplitude = 0.2,
            .noiseAmplitude = 0.1,
            .noiseCutoff = 2000.0,
            .noiseResonance = 0.7,
            .noiseEnvAttack = 100,
            .noiseEnvDecay = 400,
            .noiseEnvSustain = 0.0,
            .noiseEnvRelease = 300,
            .noiseCutoffEnvAmount = 2000.0,
            .noiseFilterType = 0,
            .noiseOctaveControl = 2.0,
            .moogOctaveControl = 2.0,
            .moogCutoff = 1500.0,
            .moogResonance = 0.6
        },
        .presetName = "Pad",
        .soundTypeIndex = 6
    },
    // Preset 7 : Sine
    {
        .sound = {
            .type = SYNTH,
            .name = "Sine",
            .synth = {
                .waveformType = WAVEFORM_SINE,
                .amplitude = 0.6,
                .attack = 10,
                .decay = 50,
                .sustain = 0.7,
                .release = 1000,
                .freqMod = 0.6,
                .phaseMod = 90,
                .ratioFm = 0.75,
                .modAmplitude = 0.2,
                .moogAttack = 50,
                .moogDecay = 200,
                .moogSustain = 0.7,
                .moogRelease = 800,
                .lpfResonance = 0.8,
                .octaveShift = 2,
                .lpfCutoff = 3000.0,
                .lpfEnvAmount = 1.5,
                .FMEnvAmount = 1.0,
                .FMWaveform = WAVEFORM_SINE,
                .lpfOctaveControl = 2.5
            }
        },
        .effects = {
            .reverbRoomSize = 0.8,
            .reverbDamping = 0.7,
            .filterFreq = 3000.0,
            .filterResonance = 0.8,
            .nChorus = 8,
            .tremoloWaveform = WAVEFORM_SINE,
            .tremoloRate = 2.0,
            .tremoloAmplitude = 0.1,
            .moogLfoWaveform = WAVEFORM_SINE,
            .moogLfoRate = 0.3,
            .moogLfoAmplitude = 0.2,
            .noiseAmplitude = 0.1,
            .noiseCutoff = 2000.0,
            .noiseResonance = 0.7,
            .noiseEnvAttack = 100,
            .noiseEnvDecay = 400,
            .noiseEnvSustain = 0.0,
            .noiseEnvRelease = 300,
            .noiseCutoffEnvAmount = 2000.0,
            .noiseFilterType = 0,
            .noiseOctaveControl = 2.0,
            .moogOctaveControl = 2.0,
            .moogCutoff = 3000.0,
            .moogResonance = 0.6
        },
        .presetName = "Sine",
        .soundTypeIndex = 7


    },
    // Preset 8 : square
    { 
        .sound = {
            .type = SYNTH,
            .name = "Square",
            .synth = {
                .waveformType = WAVEFORM_SQUARE,
                .amplitude = 0.7,
                .attack = 20,
                .decay = 50,
                .sustain = 0.4,
                .release = 200,
                .freqMod = 1.5,
                .phaseMod = 10,
                .ratioFm = 0.5,
                .modAmplitude = 0.25,
                .moogAttack = 50,
                .moogDecay = 200,
                .moogSustain = 0.7,
                .moogRelease = 800,
                .lpfResonance = 0.8,
                .octaveShift = 2,
                .lpfCutoff = 4000.0,
                .lpfEnvAmount = 1.5,
                .FMEnvAmount = 1.0,
                .FMWaveform = WAVEFORM_SINE,
                .lpfOctaveControl = 2.5
            }
        },
        .effects = {
            .reverbRoomSize = 0.9,
            .reverbDamping = 0.7,
            .filterFreq = 1000.0,
            .filterResonance = 0.8,
            .nChorus = 8,
            .tremoloWaveform = WAVEFORM_SINE,
            .tremoloRate = 2.0,
            .tremoloAmplitude = 0.1,
            .moogLfoWaveform = WAVEFORM_SINE,
            .moogLfoRate = 5,
            .moogLfoAmplitude = 0.5,
            .noiseAmplitude = 0.1,
            .noiseCutoff = 2000.0,
            .noiseResonance = 0.7,
            .noiseEnvAttack = 100,
            .noiseEnvDecay = 400,
            .noiseEnvSustain = 0.0,
            .noiseEnvRelease = 300,
            .noiseCutoffEnvAmount = 2000.0,
            .noiseFilterType = 0,
            .noiseOctaveControl = 2.0,
            .moogOctaveControl = 2.0,
            .moogCutoff = 1000.0,
            .moogResonance = 0.6
        },
        .presetName = "Square",
        .soundTypeIndex = 8
        

    },
    // Preset 9 : Mario
    {
        .sound = {
            .type = SYNTH,
            .name = "Mario",
            .synth = {
                .waveformType = WAVEFORM_SQUARE,  // typique NES
                .amplitude = 0.8,
                .attack = 2,        // attaque quasi instantanée
                .decay = 80,        // décroissance rapide
                .sustain = 0.0,     // pas de maintien
                .release = 30,      // courte libération
                .freqMod = 1.0,     // pitch normal
                .phaseMod = 0.1,
                .ratioFm = 0.1,     // pas de FM
                .modAmplitude = 0.1,
                .moogAttack = 0,
                .moogDecay = 0,
                .moogSustain = 0,
                .moogRelease = 0,
                .lpfResonance = 0.7,
                .octaveShift = 2,
                .lpfCutoff = 8000.0,
                .lpfEnvAmount = 0.0,
                .FMEnvAmount = 0.0,
                .FMWaveform = WAVEFORM_SINE,
                .lpfOctaveControl = 2.0
            }
        },
        .effects = {
            .reverbRoomSize = 0.1,     // très peu de reverb, son sec
            .reverbDamping = 0.7,
            .filterFreq = 3000.0,      // filtre large
            .filterResonance = 1.0,
            .nChorus = 0,
            .tremoloWaveform = WAVEFORM_SINE,
            .tremoloRate = 0.0,
            .tremoloAmplitude = 0.0,
            .moogLfoWaveform = WAVEFORM_SINE,
            .moogLfoRate = 0.0,
            .moogLfoAmplitude = 0.0,
            .noiseAmplitude = 0.0,
            .noiseCutoff = 0.0,
            .noiseResonance = 0.0,
            .noiseEnvAttack = 0,
            .noiseEnvDecay = 0,
            .noiseEnvSustain = 0.0,
            .noiseEnvRelease = 0,
            .noiseCutoffEnvAmount = 0.0,
            .noiseFilterType = 0,
            .noiseOctaveControl = 0.0,
            .moogOctaveControl = 0.0,
            .moogCutoff = 0.0,
            .moogResonance = 0.0
        },
        .presetName = "Mario",
        .soundTypeIndex = 9
    },
    // Preset 10 : handpan
    { 

        .sound = {
            .type = SYNTH,
            .name = "HandPan",
            .synth = {
                .waveformType = WAVEFORM_TRIANGLE,
                .amplitude = 0.6,
                .attack = 30,
                .decay = 1800,
                .sustain = 0.3,
                .release = 1000,
                .freqMod = 0.1,
                .phaseMod = 5,
                .ratioFm = 1.3,
                .modAmplitude = 0.1,
                .moogAttack = 200,
                .moogDecay = 500,
                .moogSustain = 0.7,
                .moogRelease = 800,
                .lpfResonance = 0.8,
                .octaveShift = 2,
                .lpfCutoff = 4000.0,
                .lpfEnvAmount = 1.0,
                .FMEnvAmount = 0.3,
                .FMWaveform = WAVEFORM_SINE,
                .lpfOctaveControl = 2.0
            }
        },
        .effects = {
            .reverbRoomSize = 0.9,
            .reverbDamping = 0.7,
            .filterFreq = 3000.0,
            .filterResonance = 0.6,
            .nChorus = 8,
            .tremoloWaveform = WAVEFORM_SINE,
            .tremoloRate = 2.0,
            .tremoloAmplitude = 0.1,
            .moogLfoWaveform = WAVEFORM_SINE,
            .moogLfoRate = 2.0,
            .moogLfoAmplitude = 0.5,
            .noiseAmplitude = 0.1,
            .noiseCutoff = 2000.0,
            .noiseResonance = 0.7,
            .noiseEnvAttack = 100,
            .noiseEnvDecay = 400,
            .noiseEnvSustain = 0.0,
            .noiseEnvRelease = 300,
            .noiseCutoffEnvAmount = 2000.0,
            .noiseFilterType = 0,
            .noiseOctaveControl = 2.0,
            .moogOctaveControl = 2.0,
            .moogCutoff = 3000.0,
            .moogResonance = 0.6
        },
        .presetName = "HandPan",
        .soundTypeIndex = 10
        

    },
    {

        // 11. 8-Bit Game Lead
        .sound = {
            .type = SYNTH,
            .name = "8-Bit Lead",
            .synth = {
                .waveformType = WAVEFORM_SQUARE,
                .amplitude = 0.8,
                .attack = 5,
                .decay = 30,
                .sustain = 0.7,
                .release = 100,
                .freqMod = 1.0,
                .phaseMod = 0.0,
                .ratioFm = 2,
                .modAmplitude = 0.3,
                .moogAttack = 5,
                .moogDecay = 20,
                .moogSustain = 0.8,
                .moogRelease = 50,
                .lpfResonance = 0.2,
                .octaveShift = 2,
                .lpfCutoff = 5000.0,
                .lpfEnvAmount = 0.5,
                .FMEnvAmount = 0.5,
                .FMWaveform = WAVEFORM_SQUARE,
                .lpfOctaveControl = 2.0
            }
        },
        .effects = {
            .reverbRoomSize = 0.1,
            .reverbDamping = 0.9,
            .filterFreq = 4000.0,
            .filterResonance = 0.5,
            .nChorus = 0,
            .tremoloWaveform = WAVEFORM_SQUARE,
            .tremoloRate = 8.0,
            .tremoloAmplitude = 0.2,
            .moogLfoWaveform = WAVEFORM_SQUARE,
            .moogLfoRate = 0.0,
            .moogLfoAmplitude = 0.0,
            .noiseAmplitude = 0.0,
            .noiseCutoff = 0.0,
            .noiseResonance = 0.0,
            .noiseEnvAttack = 0,
            .noiseEnvDecay = 0,
            .noiseEnvSustain = 0.0,
            .noiseEnvRelease = 0,
            .noiseCutoffEnvAmount = 0.0,
            .noiseFilterType = 0,
            .noiseOctaveControl = 0.0,
            .moogOctaveControl = 0.0,
            .moogCutoff = 0.0,
            .moogResonance = 0.0
        },
        .presetName = "8-Bit Lead",
        .soundTypeIndex = 11
    },
    {
    // 12. Kick Drum Synth
        .sound = {
            .type = SYNTH,
            .name = "Synth Kick",
            .synth = {
                .waveformType = WAVEFORM_SINE,
                .amplitude = 1.0,
                .attack = 1,
                .decay = 150,
                .sustain = 0.0,
                .release = 50,
                .freqMod = 0.2,
                .phaseMod = 0.0,
                .ratioFm = 1,
                .modAmplitude = 0.8,
                .moogAttack = 1,
                .moogDecay = 100,
                .moogSustain = 0.0,
                .moogRelease = 20,
                .lpfResonance = 0.3,
                .octaveShift = 2,
                .lpfCutoff = 1000.0,
                .lpfEnvAmount = 2.0,
                .FMEnvAmount = 1.5,
                .FMWaveform = WAVEFORM_SINE,
                .lpfOctaveControl = 3.0
            }
        },
        .effects = {
            .reverbRoomSize = 0.0,
            .reverbDamping = 1.0,
            .filterFreq = 200.0,
            .filterResonance = 0.8,
            .nChorus = 0,
            .tremoloWaveform = WAVEFORM_SINE,
            .tremoloRate = 0.0,
            .tremoloAmplitude = 0.0,
            .moogLfoWaveform = WAVEFORM_SINE,
            .moogLfoRate = 0.0,
            .moogLfoAmplitude = 0.0,
            .noiseAmplitude = 0.0,
            .noiseCutoff = 0.0,
            .noiseResonance = 0.0,
            .noiseEnvAttack = 0,
            .noiseEnvDecay = 0,
            .noiseEnvSustain = 0.0,
            .noiseEnvRelease = 0,
            .noiseCutoffEnvAmount = 0.0,
            .noiseFilterType = 0,
            .noiseOctaveControl = 0.0,
            .moogOctaveControl = 0.0,
            .moogCutoff = 0.0,
            .moogResonance = 0.0
        },
        .presetName = "Synth Kick",
        .soundTypeIndex = 12
    },
    {
        // 13. Snare Percussif
        .sound = {
            .type = SYNTH,
            .name = "Synth Snare",
            .synth = {
                .waveformType = WAVEFORM_PULSE,
                .amplitude = 0.9,
                .attack = 2,
                .decay = 80,
                .sustain = 0.1,
                .release = 40,
                .freqMod = 1.0,
                .phaseMod = 0.0,
                .ratioFm = 3,
                .modAmplitude = 0.6,
                .moogAttack = 1,
                .moogDecay = 50,
                .moogSustain = 0.0,
                .moogRelease = 30,
                .lpfResonance = 0.6,
                .octaveShift = 2,
                .lpfCutoff = 2000.0,
                .lpfEnvAmount = 1.5,
                .FMEnvAmount = 1.0,
                .FMWaveform = WAVEFORM_SINE,
                .lpfOctaveControl = 2.0
            }
            },
            .effects = {
                .reverbRoomSize = 0.2,
                .reverbDamping = 0.8,
                .filterFreq = 3000.0,
                .filterResonance = 1.5,
                .nChorus = 0,
                .tremoloWaveform = WAVEFORM_SINE,
                .tremoloRate = 0.0,
                .tremoloAmplitude = 0.0,
                .moogLfoWaveform = WAVEFORM_SINE,
                .moogLfoRate = 0.0,
                .moogLfoAmplitude = 0.0,
                .noiseAmplitude = 0.5,
                .noiseCutoff = 4000.0,
                .noiseResonance = 0.7,
                .noiseEnvAttack = 1,
                .noiseEnvDecay = 100,
                .noiseEnvSustain = 0.0,
                .noiseEnvRelease = 50,
                .noiseCutoffEnvAmount = 1500.0,
                .noiseFilterType = 0,
                .noiseOctaveControl = 2.0,
                .moogOctaveControl = 0.0,
                .moogCutoff = 0.0,
                .moogResonance = 0.0
            },
            .presetName = "Synth Snare",
            .soundTypeIndex = 13
    },
    {
        // 14. Pad Évolutif
        .sound = {
            .type = SYNTH,
            .name = "Evolving Pad",
            .synth = {
                .waveformType = WAVEFORM_SAWTOOTH,
                .amplitude = 0.5,
                .attack = 500,
                .decay = 200,
                .sustain = 0.8,
                .release = 800,
                .freqMod = 1.0,
                .phaseMod = 0.3,
                .ratioFm = 2,
                .modAmplitude = 0.4,
                .moogAttack = 300,
                .moogDecay = 400,
                .moogSustain = 0.6,
                .moogRelease = 600,
                .lpfResonance = 1.2,
                .octaveShift = 2,
                .lpfCutoff = 2500.0,
                .lpfEnvAmount = 1.5,
                .FMEnvAmount = 0.5,
                .FMWaveform = WAVEFORM_SINE,
                .lpfOctaveControl = 2.0
            }
            },
            .effects = {
                .reverbRoomSize = 0.9,
                .reverbDamping = 0.4,
                .filterFreq = 800.0,
                .filterResonance = 2.0,
                .nChorus = 3,
                .tremoloWaveform = WAVEFORM_SINE,
                .tremoloRate = 0.2,
                .tremoloAmplitude = 0.4,
                .moogLfoWaveform = WAVEFORM_SINE,
                .moogLfoRate = 0.1,
                .moogLfoAmplitude = 0.8,
                .noiseAmplitude = 0.1,
                .noiseCutoff = 2000.0,
                .noiseResonance = 0.5,
                .noiseEnvAttack = 100,
                .noiseEnvDecay = 400,
                .noiseEnvSustain = 0.0,
                .noiseEnvRelease = 300,
                .noiseCutoffEnvAmount = 1500.0,
                .noiseFilterType = 0,
                .noiseOctaveControl = 2.0,
                .moogOctaveControl = 2.0,
                .moogCutoff = 800.0,
                .moogResonance = 0.6
            },
        .presetName = "Evolving Pad",
        .soundTypeIndex = 14
    },
    {
    // 15. Basse FM Agressive
    .sound = {
    .type = SYNTH,
    .name = "FM Bass",
    .synth = {
        .waveformType = WAVEFORM_SINE,
        .amplitude = 0.9,
        .attack = 5,
        .decay = 100,
        .sustain = 0.6,
        .release = 150,
        .freqMod = 1.0,
        .phaseMod = 0.0,
        .ratioFm = 4,
        .modAmplitude = 0.9,
        .moogAttack = 10,
        .moogDecay = 80,
        .moogSustain = 0.5,
        .moogRelease = 100,
        .lpfResonance = 1.5,
        .octaveShift = 1,
        .lpfCutoff = 500.0,
        .lpfEnvAmount = 3.0,
        .FMEnvAmount = 2.0,
        .FMWaveform = WAVEFORM_SINE,
        .lpfOctaveControl = 4.0
    }
    },
    .effects = {
        .reverbRoomSize = 0.1,
        .reverbDamping = 0.9,
        .filterFreq = 400.0,
        .filterResonance = 2.5,
        .nChorus = 0,
        .tremoloWaveform = WAVEFORM_SINE,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = WAVEFORM_SINE,
        .moogLfoRate = 3.0,
        .moogLfoAmplitude = 0.5,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0.0,
        .moogOctaveControl = 0.0,
        .moogCutoff = 0.0,
        .moogResonance = 0.0
    },
    .presetName = "FM Bass",
    .soundTypeIndex = 15
    },
    {
    // 16. Laser Spatial
    .sound = {
    .type = SYNTH,
    .name = "Space Laser",
    .synth = {
        .waveformType = WAVEFORM_SAWTOOTH,
        .amplitude = 0.7,
        .attack = 1,
        .decay = 200,
        .sustain = 0.0,
        .release = 100,
        .freqMod = 0.1,
        .phaseMod = 0.5,
        .ratioFm = 5,
        .modAmplitude = 0.8,
        .moogAttack = 1,
        .moogDecay = 150,
        .moogSustain = 0.0,
        .moogRelease = 80,
        .lpfResonance = 2.0,
        .octaveShift = 2,
        .lpfCutoff = 4000.0,
        .lpfEnvAmount = 2.0,
        .FMEnvAmount = 1.5,
        .FMWaveform = WAVEFORM_SAWTOOTH,
        .lpfOctaveControl = 3.0
    }
    },
    .effects = {
        .reverbRoomSize = 0.7,
        .reverbDamping = 0.3,
        .filterFreq = 5000.0,
        .filterResonance = 3.0,
        .nChorus = 1,
        .tremoloWaveform = WAVEFORM_SINE,
        .tremoloRate = 12.0,
        .tremoloAmplitude = 0.5,
        .moogLfoWaveform = WAVEFORM_SAWTOOTH,
        .moogLfoRate = 8.0,
        .moogLfoAmplitude = 0.7,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0.0,
        .moogOctaveControl = 0.0,
        .moogCutoff = 0.0,
        .moogResonance = 0.0
    },
    .presetName = "Space Laser",
    .soundTypeIndex = 16
    },
    {
    // 17. Cloche Métallique
    .sound = {
    .type = SYNTH,
    .name = "Metal Bell",
    .synth = {
        .waveformType = WAVEFORM_SINE,
        .amplitude = 0.6,
        .attack = 2,
        .decay = 300,
        .sustain = 0.3,
        .release = 500,
        .freqMod = 1.0,
        .phaseMod = 0.0,
        .ratioFm = 7,
        .modAmplitude = 0.7,
        .moogAttack = 5,
        .moogDecay = 200,
        .moogSustain = 0.4,
        .moogRelease = 400,
        .lpfResonance = 0.4,
        .octaveShift = 2,
        .lpfCutoff = 4000.0,
        .lpfEnvAmount = 0.5,
        .FMEnvAmount = 0.0,
        .FMWaveform = WAVEFORM_SQUARE,
        .lpfOctaveControl = 0.0
    }
    },
    .effects = {
        .reverbRoomSize = 0.8,
        .reverbDamping = 0.2,
        .filterFreq = 6000.0,
        .filterResonance = 1.0,
        .nChorus = 2,
        .tremoloWaveform = WAVEFORM_SINE,
        .tremoloRate = 4.0,
        .tremoloAmplitude = 0.2,
        .moogLfoWaveform = WAVEFORM_SINE,
        .moogLfoRate = 0.0,
        .moogLfoAmplitude = 0.0,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0.0,
        .moogOctaveControl = 0.0,
        .moogCutoff = 0.0,
        .moogResonance = 0.0
    },
    .presetName = "Metal Bell",
    .soundTypeIndex = 17
    },
    {
    // 18. 8-Bit Arpège
    .sound = {
    .type = SYNTH,
    .name = "8-Bit Arp",
    .synth = {
        .waveformType = WAVEFORM_SQUARE,
        .amplitude = 0.6,
        .attack = 2,
        .decay = 50,
        .sustain = 0.3,
        .release = 50,
        .freqMod = 1.0,
        .phaseMod = 0.0,
        .ratioFm = 1,
        .modAmplitude = 0.0,
        .moogAttack = 2,
        .moogDecay = 30,
        .moogSustain = 0.5,
        .moogRelease = 40,
        .lpfResonance = 0.3,
        .octaveShift = 2,
        .lpfCutoff = 4000.0,
        .lpfEnvAmount = 0.5,
        .FMEnvAmount = 0.0,
        .FMWaveform = WAVEFORM_SQUARE,
        .lpfOctaveControl = 0.0
    }
    },
    .effects = {
        .reverbRoomSize = 0.3,
        .reverbDamping = 0.8,
        .filterFreq = 3000.0,
        .filterResonance = 0.8,
        .nChorus = 0,
        .tremoloWaveform = WAVEFORM_SQUARE,
        .tremoloRate = 16.0,
        .tremoloAmplitude = 0.3,
        .moogLfoWaveform = WAVEFORM_SQUARE,
        .moogLfoRate = 0.0,
        .moogLfoAmplitude = 0.0,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0.0,
        .moogOctaveControl = 0.0,
        .moogCutoff = 0.0,
        .moogResonance = 0.0
    },
    .presetName = "8-Bit Arp",
    .soundTypeIndex = 18
    },
    {
    // 19. Hi-Hat Synth
    .sound = {
    .type = SYNTH,
    .name = "Synth HiHat",
    .synth = {
        .waveformType = WAVEFORM_SQUARE,
        .amplitude = 0.5,
        .attack = 1,
        .decay = 40,
        .sustain = 0.0,
        .release = 20,
        .freqMod = 1.0,
        .phaseMod = 0.0,
        .ratioFm = 1,
        .modAmplitude = 0.0,
        .moogAttack = 1,
        .moogDecay = 30,
        .moogSustain = 0.0,
        .moogRelease = 15,
        .lpfResonance = 0.5,
        .octaveShift = 2,
        .lpfCutoff = 6000.0,
        .lpfEnvAmount = 1.0,
        .FMEnvAmount = 0.0,
        .FMWaveform = WAVEFORM_SQUARE,
        .lpfOctaveControl = 2.0
    }
    },
    .effects = {
        .reverbRoomSize = 0.1,
        .reverbDamping = 0.9,
        .filterFreq = 8000.0,
        .filterResonance = 1.8,
        .nChorus = 0,
        .tremoloWaveform = WAVEFORM_SINE,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = WAVEFORM_SINE,
        .moogLfoRate = 0.0,
        .moogLfoAmplitude = 0.0,
        .noiseAmplitude = 0.3,
        .noiseCutoff = 7000.0,
        .noiseResonance = 0.6,
        .noiseEnvAttack = 1,
        .noiseEnvDecay = 50,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 20,
        .noiseCutoffEnvAmount = 2000.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 2.0,
        .moogOctaveControl = 0.0,
        .moogCutoff = 0.0,
        .moogResonance = 0.0
    },
    .presetName = "Synth HiHat",
    .soundTypeIndex = 19
    },
    {
    // 20. Orgue Électrique
    .sound = {
    .type = SYNTH,
    .name = "Electric Organ",
    .synth = {
        .waveformType = WAVEFORM_SINE,
        .amplitude = 0.6,
        .attack = 10,
        .decay = 20,
        .sustain = 0.9,
        .release = 100,
        .freqMod = 1.0,
        .phaseMod = 0.0,
        .ratioFm = 2,
        .modAmplitude = 0.3,
        .moogAttack = 20,
        .moogDecay = 30,
        .moogSustain = 0.8,
        .moogRelease = 80,
        .lpfResonance = 0.6,
        .octaveShift = 2,
        .lpfCutoff = 3000.0,
        .lpfEnvAmount = 1.0,
        .FMEnvAmount = 0.5,
        .FMWaveform = WAVEFORM_SINE,
        .lpfOctaveControl = 2.0
    }
    },
    .effects = {
        .reverbRoomSize = 0.4,
        .reverbDamping = 0.6,
        .filterFreq = 2500.0,
        .filterResonance = 1.0,
        .nChorus = 3,
        .tremoloWaveform = WAVEFORM_SINE,
        .tremoloRate = 6.0,
        .tremoloAmplitude = 0.4,
        .moogLfoWaveform = WAVEFORM_SINE,
        .moogLfoRate = 0.3,
        .moogLfoAmplitude = 0.3,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0.0,
        .moogOctaveControl = 0.0,
        .moogCutoff = 0.0,
        .moogResonance = 0.0
    },
    .presetName = "Electric Organ",
    .soundTypeIndex = 20  
    },
    {
    // 21. Glitch Noise
    .sound = {
    .type = SYNTH,
    .name = "Glitch",
    .synth = {
        .waveformType = WAVEFORM_SQUARE,
        .amplitude = 0.7,
        .attack = 1,
        .decay = 30,
        .sustain = 0.5,
        .release = 50,
        .freqMod = 1.0,
        .phaseMod = 0.8,
        .ratioFm = 11,
        .modAmplitude = 0.9,
        .moogAttack = 1,
        .moogDecay = 20,
        .moogSustain = 0.6,
        .moogRelease = 40,
        .lpfResonance = 3.0,
        .octaveShift = 2,
        .lpfCutoff = 2000.0,
        .lpfEnvAmount = 2.0,
        .FMEnvAmount = 2.0,
        .FMWaveform = WAVEFORM_SQUARE,
        .lpfOctaveControl = 3.0
    }
    },
    .effects = {
        .reverbRoomSize = 0.3,
        .reverbDamping = 0.5,
        .filterFreq = 1500.0,
        .filterResonance = 4.0,
        .nChorus = 1,
        .tremoloWaveform = WAVEFORM_SQUARE,
        .tremoloRate = 32.0,
        .tremoloAmplitude = 0.7,
        .moogLfoWaveform = WAVEFORM_SQUARE,
        .moogLfoRate = 16.0,
        .moogLfoAmplitude = 0.9,
        .noiseAmplitude = 0.5,
        .noiseCutoff = 3000.0,
        .noiseResonance = 2.0,
        .noiseEnvAttack = 1,
        .noiseEnvDecay = 50,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 20,
        .noiseCutoffEnvAmount = 1500.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 2.0,
        .moogOctaveControl = 0.0,
        .moogCutoff = 0.0,
        .moogResonance = 0.0
        
    },
    .presetName = "Glitch",
    .soundTypeIndex = 21
    },
    { 
    // 22. Sirène de Police
    .sound = {
    .type = SYNTH,
    .name = "Police Siren",
    .synth = {
        .waveformType = WAVEFORM_SQUARE,
        .amplitude = 0.8,
        .attack = 50,
        .decay = 100,
        .sustain = 0.8,
        .release = 150,
        .freqMod = 1.0,
        .phaseMod = 0.0,
        .ratioFm = 1,
        .modAmplitude = 0.0,
        .moogAttack = 100,
        .moogDecay = 200,
        .moogSustain = 0.9,
        .moogRelease = 150,
        .lpfResonance = 0.5,
        .octaveShift = 2,
        .lpfCutoff = 4000.0,
        .lpfEnvAmount = 1.0,
        .FMEnvAmount = 0.0,
        .FMWaveform = WAVEFORM_SQUARE,
        .lpfOctaveControl = 2.0
    }
    },
    .effects = {
        .reverbRoomSize = 0.5,
        .reverbDamping = 0.6,
        .filterFreq = 3000.0,
        .filterResonance = 1.5,
        .nChorus = 0,
        .tremoloWaveform = WAVEFORM_SINE,
        .tremoloRate = 2.0,
        .tremoloAmplitude = 0.6,
        .moogLfoWaveform = WAVEFORM_TRIANGLE,
        .moogLfoRate = 1.5,
        .moogLfoAmplitude = 1.0,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0.0,
        .moogOctaveControl = 0.0,
        .moogCutoff = 0.0,
        .moogResonance = 0.0
    },
    .presetName = "Police Siren",
    .soundTypeIndex = 22
    },
    {
    // 23. Basse Dubstep Wobble
    .sound = {
    .type = SYNTH,
    .name = "Wobble Bass",
    .synth = {
        .waveformType = WAVEFORM_SAWTOOTH,
        .amplitude = 0.9,
        .attack = 10,
        .decay = 50,
        .sustain = 0.8,
        .release = 100,
        .freqMod = 1.0,
        .phaseMod = 0.0,
        .ratioFm = 1,
        .modAmplitude = 0.0,
        .moogAttack = 5,
        .moogDecay = 30,
        .moogSustain = 0.9,
        .moogRelease = 50,
        .lpfResonance = 4.0,
        .octaveShift = 1,
        .lpfCutoff = 600.0,
        .lpfEnvAmount = 4.0,
        .FMEnvAmount = 0.0,
        .FMWaveform = WAVEFORM_SAWTOOTH,
        .lpfOctaveControl = 5.0
    }
    },
    .effects = {
        .reverbRoomSize = 0.2,
        .reverbDamping = 0.8,
        .filterFreq = 500.0,
        .filterResonance = 5.0,
        .nChorus = 0,
        .tremoloWaveform = WAVEFORM_SINE,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = WAVEFORM_SINE,
        .moogLfoRate = 6.0,
        .moogLfoAmplitude = 1.0,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0.0,
        .moogOctaveControl = 0.0,
        .moogCutoff = 0.0,
        .moogResonance = 0.0
    },
    .presetName = "Wobble Bass",
    .soundTypeIndex = 23
    
    },
    {
    // 24. Coin Collecté (jeu vidéo)
    .sound = {
    .type = SYNTH,
    .name = "Coin Pickup",
    .synth = {
        .waveformType = WAVEFORM_SQUARE,
        .amplitude = 0.7,
        .attack = 1,
        .decay = 80,
        .sustain = 0.0,
        .release = 30,
        .freqMod = 2.0,
        .phaseMod = 0.0,
        .ratioFm = 2,
        .modAmplitude = 0.5,
        .moogAttack = 1,
        .moogDecay = 50,
        .moogSustain = 0.0,
        .moogRelease = 20,
        .lpfResonance = 0.4,
        .octaveShift = 2,
        .lpfCutoff = 5000.0,
        .lpfEnvAmount = 1.0,
        .FMEnvAmount = 1.0,
        .FMWaveform = WAVEFORM_SINE,
        .lpfOctaveControl = 2.0
    }
    },
    .effects = {
        .reverbRoomSize = 0.2,
        .reverbDamping = 0.7,
        .filterFreq = 4000.0,
        .filterResonance = 0.8,
        .nChorus = 1,
        .tremoloWaveform = WAVEFORM_SINE,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = WAVEFORM_SINE,
        .moogLfoRate = 0.0,
        .moogLfoAmplitude = 0.0,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0.0,
        .moogOctaveControl = 0.0,
        .moogCutoff = 0.0,
        .moogResonance = 0.0
    },
    .presetName = "Coin Pickup",
    .soundTypeIndex = 24
    },
    {
    // 25. Ambient Drone
    .sound = {
    .type = SYNTH,
    .name = "Ambient Drone",
    .synth = {
        .waveformType = WAVEFORM_SAWTOOTH,
        .amplitude = 0.4,
        .attack = 1000,
        .decay = 500,
        .sustain = 0.9,
        .release = 1500,
        .freqMod = 1.0,
        .phaseMod = 0.2,
        .ratioFm = 3,
        .modAmplitude = 0.3,
        .moogAttack = 800,
        .moogDecay = 600,
        .moogSustain = 0.8,
        .moogRelease = 1200,
        .lpfResonance = 1.5,
        .octaveShift = 2,
        .lpfCutoff = 2000.0,
        .lpfEnvAmount = 2.0,
        .FMEnvAmount = 0.5,
        .FMWaveform = WAVEFORM_SINE,
        .lpfOctaveControl = 2.0
    }
    },
    .effects = {
        .reverbRoomSize = 1.0,
        .reverbDamping = 0.3,
        .filterFreq = 600.0,
        .filterResonance = 2.5,
        .nChorus = 3,
        .tremoloWaveform = WAVEFORM_SINE,
        .tremoloRate = 0.1,
        .tremoloAmplitude = 0.3,
        .moogLfoWaveform = WAVEFORM_SINE,
        .moogLfoRate = 0.05,
        .moogLfoAmplitude = 0.7,
        .noiseAmplitude = 0.1,
        .noiseCutoff = 1500.0,
        .noiseResonance = 0.5,
        .noiseEnvAttack = 500,
        .noiseEnvDecay = 800,
        .noiseEnvSustain = 0.2,
        .noiseEnvRelease = 1000,
        .noiseCutoffEnvAmount = 1000.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 2.0,
        .moogOctaveControl = 2.0,
        .moogCutoff = 800.0,
        .moogResonance = 0.6
    },
    .presetName = "Ambient Drone",
    .soundTypeIndex = 25
    },
    {
    // 26. Explosion
    .sound = {
    .type = SYNTH,
    .name = "Explosion",
    .synth = {
        .waveformType = WAVEFORM_SQUARE,
        .amplitude = 1.0,
        .attack = 1,
        .decay = 300,
        .sustain = 0.0,
        .release = 200,
        .freqMod = 0.1,
        .phaseMod = 0.0,
        .ratioFm = 1,
        .modAmplitude = 0.5,
        .moogAttack = 1,
        .moogDecay = 250,
        .moogSustain = 0.0,
        .moogRelease = 150,
        .lpfResonance = 0.8,
        .octaveShift = 2,
        .lpfCutoff = 1000.0,
        .lpfEnvAmount = 3.0,
        .FMEnvAmount = 0.0,
        .FMWaveform = WAVEFORM_SQUARE,
        .lpfOctaveControl = 4.0
    }
    },
    .effects = {
        .reverbRoomSize = 0.7,
        .reverbDamping = 0.4,
        .filterFreq = 800.0,
        .filterResonance = 1.2,
        .nChorus = 0,
        .tremoloWaveform = WAVEFORM_SINE,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = WAVEFORM_SINE,
        .moogLfoRate = 0.0,
        .moogLfoAmplitude = 0.0,
        .noiseAmplitude = 0.8,
        .noiseCutoff = 2000.0,
        .noiseResonance = 1.0,
        .noiseEnvAttack = 1,
        .noiseEnvDecay = 200,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 100,
        .noiseCutoffEnvAmount = 2000.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 3.0,
        .moogOctaveControl = 0.0,
        .moogCutoff = 0.0,
        .moogResonance = 0.0
    },
    .presetName = "Explosion",
    .soundTypeIndex = 26
    },
    {
    // 27. Pluck Électrique
    .sound = {
    .type = SYNTH,
    .name = "Electric Pluck",
    .synth = {
        .waveformType = WAVEFORM_SAWTOOTH,
        .amplitude = 0.8,
        .attack = 1,
        .decay = 150,
        .sustain = 0.2,
        .release = 100,
        .freqMod = 1.0,
        .phaseMod = 0.0,
        .ratioFm = 3,
        .modAmplitude = 0.6,
        .moogAttack = 1,
        .moogDecay = 100,
        .moogSustain = 0.1,
        .moogRelease = 80,
        .lpfResonance = 1.8,
        .octaveShift = 2,
        .lpfCutoff = 3000.0,
        .lpfEnvAmount = 3.0,
        .FMEnvAmount = 1.0,
        .FMWaveform = WAVEFORM_SAWTOOTH,
        .lpfOctaveControl = 4.0
    }
    },
    .effects = {
        .reverbRoomSize = 0.3,
        .reverbDamping = 0.7,
        .filterFreq = 3500.0,
        .filterResonance = 2.0,
        .nChorus = 1,
        .tremoloWaveform = WAVEFORM_SINE,
        .tremoloRate = 0.0,
        .tremoloAmplitude = 0.0,
        .moogLfoWaveform = WAVEFORM_SINE,
        .moogLfoRate = 10.0,
        .moogLfoAmplitude = 0.5,
        .noiseAmplitude = 0.0,
        .noiseCutoff = 0.0,
        .noiseResonance = 0.0,
        .noiseEnvAttack = 0,
        .noiseEnvDecay = 0,
        .noiseEnvSustain = 0.0,
        .noiseEnvRelease = 0,
        .noiseCutoffEnvAmount = 0.0,
        .noiseFilterType = 0,
        .noiseOctaveControl = 0.0,
        .moogOctaveControl = 0.0,
        .moogCutoff = 0.0,
        .moogResonance = 0.0
    },
    .presetName = "Electric Pluck",
    .soundTypeIndex = 27
    },
    {
        // 28. Wind/Souffle Évolutif
        .sound = {
        .type = SYNTH,
        .name = "Wind Evolve",
        .synth = {
            .waveformType = WAVEFORM_TRIANGLE,
            .amplitude = 0.5,
            .attack = 800,
            .decay = 400,
            .sustain = 0.7,
            .release = 1000,
            .freqMod = 1.0,
            .phaseMod = 0.1,
            .ratioFm = 1,
            .modAmplitude = 0.2,
            .moogAttack = 600,
            .moogDecay = 500,
            .moogSustain = 0.6,
            .moogRelease = 900,
            .lpfResonance = 0.8,
            .octaveShift = 2,
            .lpfCutoff = 1500.0,
            .lpfEnvAmount = 2.0,
            .FMEnvAmount = 0.3,
            .FMWaveform = WAVEFORM_SINE,
            .lpfOctaveControl = 2.0
        }
        },
        .effects = {
            .reverbRoomSize = 0.9,
            .reverbDamping = 0.5,
            .filterFreq = 1200.0,
            .filterResonance = 1.5,
            .nChorus = 2,
            .tremoloWaveform = WAVEFORM_SINE,
            .tremoloRate = 0.3,
            .tremoloAmplitude = 0.5,
            .moogLfoWaveform = WAVEFORM_SINE,
            .moogLfoRate = 0.2,
            .moogLfoAmplitude = 0.8,
            .noiseAmplitude = 0.2,
            .noiseCutoff = 1000.0,
            .noiseResonance = 0.5,
            .noiseEnvAttack = 500,
            .noiseEnvDecay = 600,
            .noiseEnvSustain = 0.3,
            .noiseEnvRelease = 800,
            .noiseCutoffEnvAmount = 800.0,
            .noiseFilterType = 0,
            .noiseOctaveControl = 2.0,
            .moogOctaveControl = 2.0,
            .moogCutoff = 700.0,
            .moogResonance = 0.6
        },
        .presetName = "Wind Evolve",
        .soundTypeIndex = 28
    },

    // Preset 29 : pluck
    { 

        .sound = {
            .type = STRING,
            .name = "Pluck",
            .string = {
                .velocity = 0.8,
                .moogAttack = 20,
                .moogDecay = 50,
                .moogSustain = 0.7,
                .moogRelease = 80,
                .octaveShift = 2
            }
        },
        .effects = {
            .reverbRoomSize = 0.9,
            .reverbDamping = 0.7,
            .filterFreq = 3000.0,
            .filterResonance = 0.6,
            .nChorus = 8,
            .tremoloWaveform = WAVEFORM_SINE,
            .tremoloRate = 2.0,
            .tremoloAmplitude = 0.1,
            .moogLfoWaveform = WAVEFORM_SINE,
            .moogLfoRate = 2.0,
            .moogLfoAmplitude = 0.5,
            .noiseAmplitude = 0.0,
            .noiseCutoff = 0.0,
            .noiseResonance = 0.0,
            .noiseEnvAttack = 0,
            .noiseEnvDecay = 0,
            .noiseEnvSustain = 0.0,
            .noiseEnvRelease = 0,
            .noiseCutoffEnvAmount = 0.0,
            .noiseFilterType = 0,
            .noiseOctaveControl = 0.0,
            .moogOctaveControl = 0.0,
            .moogCutoff = 0.0,
            .moogResonance = 0.0
        },
        .presetName = "Pluck",
        .soundTypeIndex = 29
        

    },
    // Preset 30 : Boom
    { 

        .sound = {
            .type = DRUM,
            .name = "Boom",
            .drum = {
                .length = 50,
                .secondMix = 0.8,
                .pitchMod = 0.55,
                .moogAttack = 20,
                .moogDecay = 30,
                .moogSustain = 0.7,
                .moogRelease = 30,
                .octaveShift = 1
            }
        },
        .effects = {
            .reverbRoomSize = 0.9,
            .reverbDamping = 0.7,
            .filterFreq = 1000.0,
            .filterResonance = 0.6,
            .nChorus = 8,
            .tremoloWaveform = WAVEFORM_SINE,
            .tremoloRate = 2.0,
            .tremoloAmplitude = 0.1,
            .moogLfoWaveform = WAVEFORM_SINE,
            .moogLfoRate = 2.0,
            .moogLfoAmplitude = 0.5,
            .noiseAmplitude = 0.0,
            .noiseCutoff = 0.0,
            .noiseResonance = 0.0,
            .noiseEnvAttack = 0,
            .noiseEnvDecay = 0,
            .noiseEnvSustain = 0.0,
            .noiseEnvRelease = 0,
            .noiseCutoffEnvAmount = 0.0,
            .noiseFilterType = 0,
            .noiseOctaveControl = 0.0,
            .moogOctaveControl = 0.0,
            .moogCutoff = 0.0,
            .moogResonance = 0.0
        },
        .presetName = "Boom",
        .soundTypeIndex = 30
        

    },
    // Preset 31 : drums
    { 

        .sound = {
            .type = SAMPLE,
            .name = "Drums",
            .sample = {
            .filename = {"kick", "snare", "openHH", "closedHH", "cowbell", "lowConga", "rimShot", 
                "tabla1", "tabla2", "tabla3", "tabla4", "tabla5"},
            .moogAttack = 20,
            .moogDecay = 30,
            .moogSustain = 0.7,
            .moogRelease = 30,
            }
        },
        .effects = {
            .reverbRoomSize = 0.5,
            .reverbDamping = 0.7,
            .filterFreq = 1000.0,
            .filterResonance = 0.6,
            .moogLfoWaveform = WAVEFORM_SINE,
            .moogLfoRate = 2.0,
            .moogLfoAmplitude = 0.5,
            .noiseAmplitude = 0.0,
            .noiseCutoff = 0.0,
            .noiseResonance = 0.0,
            .noiseEnvAttack = 0,
            .noiseEnvDecay = 0,
            .noiseEnvSustain = 0.0,
            .noiseEnvRelease = 0,
            .noiseCutoffEnvAmount = 0.0,
            .noiseFilterType = 0,
            .noiseOctaveControl = 0.0,
            .moogOctaveControl = 0.0,
            .moogCutoff = 0.0,
            .moogResonance = 0.0
        },
        .presetName = "Drums",
        .soundTypeIndex = 31 
    }
};

// Banque modifiable
//extern Preset presetBank[NUM_PRESETS];

// ========== FONCTIONS ==========

// void initPresets() {
//     for (int i = 0; i < NUM_PRESETS; i++) {
//         presetBank[i] = DEFAULT_PRESETS[i];
//     }
// }

// void loadPreset(int index) {
//     if (index >= 0 && index < NUM_PRESETS) {
//         // Appliquer le preset
//         Serial.print("Preset chargé: ");
//         Serial.println(presetBank[index].presetName);
//     }
// }

// === Fonction utilitaire ===
inline const Preset& getPreset(int index) {
    return DEFAULT_PRESETS[index % NUM_PRESETS];  // Modulo = toujours valide
}

